### ISSUE TITLE
OpenID Auth: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by JonathonScott** [opendistro-for-elasticsearch/security#1069]
Q | A
-- | --
Bug? | y
New Feature? | n
Related issues | #21 #1056
Version used | amazon/opendistro-for-elasticsearch:1.7.0, amazon/opendistro-for-elasticsearch:1.12.0

**Actual Behavior**

Configuring OpenID authentication with Keycloak as test IdP. The root CA of Keycloak server certificate is configured as pemtrustedcas_filepath.

Still on trying to authenticate with Elasticsearch, it throws an unable to find valid certification path to requested target

exception:
```
[2021-03-03T18:13:20,258][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [LT-0340-001433] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-03-03T18:13:20,465][INFO ][c.a.d.a.h.j.k.JwtVerifier] [LT-0340-001433] Escaped Key ID from JWT Token
[2021-03-03T18:13:20,466][INFO ][c.a.d.a.h.j.k.SelfRefreshingKeySet] [LT-0340-001433] Performing refresh 1
[2021-03-03T18:13:20,913][INFO ][c.a.d.a.h.j.AbstractHTTPJwtAuthenticator] [LT-0340-001433] com.amazon.dlic.auth.http.jwt.keybyoidc.AuthenticatorUnavailableException: Authentication backend failed
[2021-03-03T18:13:20,915][WARN ][c.a.o.s.a.BackendRegistry] [LT-0340-001433] Authentication finally failed for null from [::1]:51504
[2021-03-03T18:13:20,911][WARN ][c.a.d.a.h.j.k.SelfRefreshingKeySet] [LT-0340-001433] KeySetProvider threw error
com.amazon.dlic.auth.http.jwt.keybyoidc.AuthenticatorUnavailableException: Error while getting https://keycloak:30011/auth/realms/realmName/.well-known/openid-configuration: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:149) ~[opendistro_security-1.7.0.0.jar:1.7.0.0]
	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.get(KeySetRetriever.java:70) ~[opendistro_security-1.7.0.0.jar:1.7.0.0]
	at com.amazon.dlic.auth.http.jwt.keybyoidc.SelfRefreshingKeySet$1.run(SelfRefreshingKeySet.java:214) [opendistro_security-1.7.0.0.jar:1.7.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:645) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:464) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360) ~[?:?]
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:181) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1460) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1368) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437) ~[?:?]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.3.jar:4.5.3]
```

**Expected Behavior**

With the right root CA configured in pemtrustedcas_filepath it should connect to the OpenID connect url to retrieve the metadata.

**Steps to Reproduce**

Given the following configuration:

```
     openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            enable_ssl: true
            pemtrustedcas_filepath: /usr/share/elasticsearch/config/keycloak-ca.crt # or relative path to config directory keycloak-ca.crt
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: https://keycloak:30011/auth/realms/realmName/.well-known/openid-configuration
        authentication_backend:
          type: noop
```

Created certs for keycloak using the following steps:

```
# create CA key
openssl genrsa -out keycloak-ca.key 2048

# create CA certificate
openssl req -x509 -new -nodes -sha256 -days 3650 -subj "/CN=example.com" \
  -key keycloak-ca.key -out keycloak-ca.crt

# create keycloak server private key
openssl genrsa -out keycloak.key 2048

# prepare certificate configuration 
# On your system the location of the file may be elsewhere.
# You may try:
#     /etc/pki/tls/openssl.cnf
#     /usr/local/ssl/openssl.cnf
#     
cp /etc/ssl/openssl.cnf ssl.cnf
cat >> ssl.cnf << EOF
 [ SAN ]
 basicConstraints = CA:FALSE
 keyUsage = digitalSignature, keyEncipherment
 subjectAltName = DNS:keycloak
EOF

# create certificate-signing request
openssl req -new -sha256 \
  -key keycloak.key \
  -subj "/CN=keycloak" \
  -reqexts SAN \
  -config ssl.cnf \
  -out keycloak.csr

# Generate the final keycloak certificate, signed by CA
openssl x509 -req -extfile ssl.cnf -extensions SAN -in keycloak.csr -CA keycloak-ca.crt \
  -CAkey keycloak-ca.key -CAcreateserial -out keycloak.crt -days 365 -sha256
```

Can connect to Keycloak using curl and the created keycloak-ca.crt

Using .crt from inside the pod: ... works fine.
```
[root@elastic-open-elasticsearch-0 elasticsearch]# curl --cacert ./config/keycloak-ca.crt https://keycloak:30011/auth/realms/realmName/.well-known/openid-configuration/
{"issuer":"https://keycloak:30011/auth/realms/realmName","authorization_endpoint":"https://keycloak:30011/auth/realms/realmName/protocol/openid-connect/auth","token_endpoint":"https://keycloak:30011/auth/realms/realmName/protocol/openid-connect/token","introspection_endpoint":"https://keycloak:30011/auth/realms/realmName/protocol/openid-connect/token/introspect","userinfo_endpoint":"https://keycloak:30011/auth/realms/realmName/protocol/openid-connect/userinfo","end_session_endpoint":"https://keycloak:30011/auth/realms/realmName/protocol/openid-connect/logout","jwks_uri":"https://keycloak:30011/auth/realms/realmName/protocol/openid-connect/certs","check_session_iframe":"https://keycloak:30011/auth/realms/realmName/protocol/openid-connect/login-status-iframe.html","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"id_token_encryption_alg_values_supported":["RSA-OAEP","RSA1_5"],"id_token_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"userinfo_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"request_object_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"response_modes_supported":["query","fragment","form_post"],"registration_endpoint":"https://keycloak:30011/auth/realms/realmName/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"token_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"claims_supported":["aud","sub","iss","auth_time","name","given_name","family_name","preferred_username","email","acr"],"claim_types_supported":["normal"],"claims_parameter_supported":false,"scopes_supported":["openid","address","web-origins","roles","offline_access","microprofile-jwt","profile","phone","email"],"request_parameter_supported":true,"request_uri_parameter_supported":true,"code_challenge_methods_supported"

```

**Comment by JonathonScott** [comment]
Tested with version 1.7.0, and version 1.12.0. Tested running elasticsearch locally as a process and having the keycloak-ca.crt in /etc/elasticsearch/ and also tested running in a pod in a kubernetes on minikube the the keycloak-ca.crt being under the config directory. Tested with full path and relative path in the security configuration and get same SSL exception.

**Comment by vrozov** [comment]
Duplicate of #1056
