### ISSUE TITLE
_field_caps API fails with cross cluster search

### ISSUE THREAD

**Issue by jimmyjones2** [opendistro-for-elasticsearch/security#1103]
Reported in a few forum threads:
* https://discuss.opendistrocommunity.dev/t/cross-cluster-search-with-secured-clusters/5162/7
* https://discuss.opendistrocommunity.dev/t/cross-cluster-search-with-secured-local-and-remote-clusters/5109/3
* https://discuss.opendistrocommunity.dev/t/kibana-ccs-fails/5405

Was working on 1.9.0, 1.10.1, 1.11. Fails on 1.12.0, 1.13.0 and 1.13.1

I’m trying to use Kibana to search indices in a remote cluster - following [CCS docs](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/cross-cluster-search/)

When I try and add an index pattern for odfe-cluster1:books I can see a 404 to http://127.0.0.1:5601/api/index_patterns/_fields_for_wildcard?pattern=odfe-cluster1%3Abooks&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score

Digging into the source for what that calls, it looks like the `_field_caps` API doesn’t support CCS:
```
curl -XGET -k -u booksuser:password 'https://localhost:9250/odfe-cluster1:books/_field_caps?fields=_id'
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [odfe-cluster1:books]","resource.type":"index_or_alias","resource.id":"odfe-cluster1:books","index_uuid":"_na_","index":"odfe-cluster1:books"}],"type":"index_not_found_exception","reason":"no such index [odfe-cluster1:books]","resource.type":"index_or_alias","resource.id":"odfe-cluster1:books","index_uuid":"_na_","index":"odfe-cluster1:books"},"status":404}
```

As this works without the security plugin installed, I presume the issue is there.

**Comment by vrozov** [comment]
Please provide ES logs for both source and target clusters.

**Comment by jimmyjones2** [comment]
Thanks @vrozov! Upped the logging on both, nothing on the remote cluster, but this on the coordinating cluster:
```
[2021-03-26T21:00:45,514][DEBUG][c.a.o.s.a.BackendRegistry] [b21aa2c0276a] Check authdomain for rest internal/4 or 1 in total
[2021-03-26T21:00:45,514][DEBUG][c.a.o.s.a.BackendRegistry] [b21aa2c0276a] Rest user 'User [name=admin, backend_roles=[admin], requestedTenant=null]' is authenticated
[2021-03-26T21:00:45,514][DEBUG][c.a.o.s.a.BackendRegistry] [b21aa2c0276a] securitytenant 'null'
[2021-03-26T21:00:45,514][DEBUG][c.a.o.s.p.PrivilegesEvaluator] [b21aa2c0276a] ### evaluate permissions for User [name=admin, backend_roles=[admin], requestedTenant=null] on b21aa2c0276a
[2021-03-26T21:00:45,514][DEBUG][c.a.o.s.p.PrivilegesEvaluator] [b21aa2c0276a] action: indices:data/read/field_caps (FieldCapabilitiesRequest)
[2021-03-26T21:00:45,514][DEBUG][c.a.o.s.p.PrivilegesEvaluator] [b21aa2c0276a] mapped roles: [own_index, all_access]
[2021-03-26T21:00:45,514][DEBUG][c.a.o.s.r.IndexResolverReplacer] [b21aa2c0276a] Resolve aliases, indices and types from FieldCapabilitiesRequest
[2021-03-26T21:00:45,515][DEBUG][c.a.o.s.p.PrivilegesEvaluator] [b21aa2c0276a] requestedResolved : Resolved [aliases=[], allIndices=[], types=[*], originalRequested=[odfe-cluster1:books], remoteIndices=[odfe-cluster1:books]]
[2021-03-26T21:00:45,515][DEBUG][c.a.o.s.p.PrivilegesEvaluator] [b21aa2c0276a] requested [indices:data/read/field_caps] from 10.88.0.1:38068
[2021-03-26T21:00:45,515][DEBUG][c.a.o.s.p.PrivilegesEvaluator] [b21aa2c0276a] requested resolved indextypes: Resolved [aliases=[], allIndices=[], types=[*], originalRequested=[odfe-cluster1:books], remoteIndices=[odfe-cluster1:books]]
[2021-03-26T21:00:45,515][DEBUG][c.a.o.s.p.PrivilegesEvaluator] [b21aa2c0276a] sr: [own_index, all_access]
[2021-03-26T21:00:45,515][DEBUG][c.a.o.s.c.PrivilegesInterceptorImpl] [b21aa2c0276a] raw requestedTenant: 'null'
[2021-03-26T21:00:45,515][DEBUG][c.a.o.s.p.PrivilegesEvaluator] [b21aa2c0276a] Result from privileges interceptor: com.amazon.opendistroforelasticsearch.security.privileges.PrivilegesInterceptor$ReplaceResult@7f1d6e52
[2021-03-26T21:00:45,515][DEBUG][c.a.o.s.p.PrivilegesEvaluator] [b21aa2c0276a] sr2: [own_index, all_access]
[2021-03-26T21:00:45,515][DEPRECATION][o.e.d.c.m.IndexNameExpressionResolver] [b21aa2c0276a] this request accesses system indices: [.kibana_1], but in a future major version, direct access to system indices will be prevented by default
[2021-03-26T21:00:45,515][DEBUG][c.a.o.s.p.PrivilegesEvaluator] [b21aa2c0276a] Allowed because we have all indices permissions for indices:data/read/field_caps
[2021-03-26T21:00:45,515][DEBUG][c.a.o.s.f.OpenDistroSecurityFilter] [b21aa2c0276a] PrivEvalResponse [allowed=true, missingPrivileges=[indices:data/read/field_caps], allowedFlsFields=null, maskedFields=null, queries=null]
```

**Comment by jimmyjones2** [comment]
Upped to TRACE and got:
```
[2021-03-26T21:51:25,853][TRACE][o.e.a.f.TransportFieldCapabilitiesAction] [9c4c28312dbd] Error during transport action execution.
org.elasticsearch.index.IndexNotFoundException: no such index [odfe-cluster1:books]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameExpressionResolver.java:945) ~[elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:882) ~[elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:838) ~[elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:217) ~[elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:197) ~[elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:126) ~[elasticsearch-7.10.2.jar:7.10.2]
	at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.actionfilter.FieldCapsFilter.apply(FieldCapsFilter.kt:60) ~[?:?]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:177) [elasticsearch-7.10.2.jar:7.10.2]
	at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply0(OpenDistroSecurityFilter.java:311) [opendistro_security-1.13.1.0.jar:1.13.1.0]
	at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply(OpenDistroSecurityFilter.java:151) [opendistro_security-1.13.1.0.jar:1.13.1.0]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:177) [elasticsearch-7.10.2.jar:7.10.2]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:77) [opendistro-performance-analyzer-1.13.0.0.jar:1.13.0.0]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:177) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:155) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:83) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:86) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:75) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:412) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.client.support.AbstractClient.fieldCaps(AbstractClient.java:650) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.rest.action.RestFieldCapabilitiesAction.lambda$prepareRequest$1(RestFieldCapabilitiesAction.java:69) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:115) [elasticsearch-7.10.2.jar:7.10.2]
	at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityRestFilter$1.handleRequest(OpenDistroSecurityRestFilter.java:116) [opendistro_security-1.13.1.0.jar:1.13.1.0]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:258) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:340) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:191) [elasticsearch-7.10.2.jar:7.10.2]
	at com.amazon.opendistroforelasticsearch.security.ssl.http.netty.ValidatingDispatcher.dispatchRequest(ValidatingDispatcher.java:63) [opendistro_security-1.13.1.0.jar:1.13.1.0]
	at org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:319) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:384) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:309) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:42) [transport-netty4-client-7.10.2.jar:7.10.2]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:28) [transport-netty4-client-7.10.2.jar:7.10.2]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:58) [transport-netty4-client-7.10.2.jar:7.10.2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```
