### ISSUE TITLE
Error in static initialization of OSGlobals with exception in docker image in security plugin

### ISSUE THREAD

**Issue by ruffy91** [opendistro-for-elasticsearch/security#12]
I get the following error when starting the open distro for elasticsearch docker image

```
[2019-03-17T21:24:13,750][INFO ][o.e.c.r.a.AllocationService] [r2SNuFs] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.opendistro_security][0]] ...]).
[2019-03-17T21:24:13,865][ERROR][c.a.o.s.a.BackendRegistry] [r2SNuFs] Not yet initialized (you may need to run securityadmin)
[2019-03-17T21:24:13,903][INFO ][c.a.o.s.c.IndexBaseConfigurationRepository] [r2SNuFs] Node 'r2SNuFs' initialized
[2019-03-17T21:24:14,414][ERROR][c.a.o.e.p.o.OSGlobals ] [r2SNuFs] Error in static initialization of OSGlobals with exception: java.security.AccessControlException: access denied ("java.io.FilePermission" "/proc/self/task" "read")
java.security.AccessControlException: access denied ("java.io.FilePermission" "/proc/self/task" "read")
at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
at java.security.AccessController.checkPermission(AccessController.java:895) ~[?:?]
at java.lang.SecurityManager.checkPermission(SecurityManager.java:322) ~[?:?]
at java.lang.SecurityManager.checkRead(SecurityManager.java:661) ~[?:?]
at java.io.File.list(File.java:1129) ~[?:?]
at java.io.File.listFiles(File.java:1219) ~[?:?]
at com.amazon.opendistro.elasticsearch.performanceanalyzer.os.OSGlobals.enumTids(OSGlobals.java:81) ~[opendistro_performance_analyzer-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistro.elasticsearch.performanceanalyzer.os.OSGlobals.<clinit>(OSGlobals.java:44) [opendistro_performance_analyzer-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistro.elasticsearch.performanceanalyzer.metrics_generator.linux.LinuxOSMetricsGenerator.getPid(LinuxOSMetricsGenerator.java:50) [opendistro_performance_analyzer-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistro.elasticsearch.performanceanalyzer.jvm.ThreadList.<clinit>(ThreadList.java:52) [opendistro_performance_analyzer-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistro.elasticsearch.performanceanalyzer.metrics.ThreadIDUtil.getNativeThreadId(ThreadIDUtil.java:31) [opendistro_performance_analyzer-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistro.elasticsearch.performanceanalyzer.metrics.ThreadIDUtil.getNativeCurrentThreadId(ThreadIDUtil.java:27) [opendistro_performance_analyzer-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistro.elasticsearch.performanceanalyzer.transport.PerformanceAnalyzerTransportChannel.set(PerformanceAnalyzerTransportChannel.java:51) [opendistro_performance_analyzer-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistro.elasticsearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.getShardBulkChannel(PerformanceAnalyzerTransportRequestHandler.java:78) [opendistro_performance_analyzer-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistro.elasticsearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.getChannel(PerformanceAnalyzerTransportRequestHandler.java:52) [opendistro_performance_analyzer-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistro.elasticsearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43) [opendistro_performance_analyzer-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistroforelasticsearch.security.ssl.transport.OpenDistroSecuritySSLRequestHandler.messageReceivedDecorate(OpenDistroSecuritySSLRequestHandler.java:183) [opendistro_security_ssl-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistroforelasticsearch.security.transport.OpenDistroSecurityRequestHandler.messageReceivedDecorate(OpenDistroSecurityRequestHandler.java:153) [opendistro_security-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistroforelasticsearch.security.ssl.transport.OpenDistroSecuritySSLRequestHandler.messageReceived(OpenDistroSecuritySSLRequestHandler.java:105) [opendistro_security_ssl-0.7.0.0.jar:0.7.0.0]
at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin$7$1.messageReceived(OpenDistroSecurityPlugin.java:651) [opendistro_security-0.7.0.0.jar:0.7.0.0]
at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.5.4.jar:6.5.4]
at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:717) [elasticsearch-6.5.4.jar:6.5.4]
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.5.4.jar:6.5.4]
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.4.jar:6.5.4]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
[2019-03-17T21:24:15,528][INFO ][o.e.n.Node               ] [r2SNuFs] stopping ...
```
I start the image with the following
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: discovery.type
          value: single-node

**Comment by ditac** [comment]
Thanks for reporting this issue. Can you please share the complete docker compose file and the steps to repro the issue. Also, a couple of questions - 
* Does this happen each time you run docker?
* Does the docker container always exit after this error, or does it continue to run?

**Comment by ruffy91** [comment]
This happens every time starting the container. The container continues to run.
I deploy the Image as pod in kubernetes with the demo config:
```
apiVersion: v1
kind: Pod
spec:
  containers:
  - env:
    - name: discovery.type
      value: single-node
    image: amazon/opendistro-for-elasticsearch
    imagePullPolicy: Always
    name: elasticsearch
    ports:
    - containerPort: 9200
      name: 9200tcp01
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {}
      privileged: false
      procMount: Default
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-ln24g
      readOnly: true
```
On first start this error is shown but elasticsearch continues to run

I first had wrong healthchecks that failed an restarted the Pod every minute, which made me think the problem is this error.

**Comment by ditac** [comment]
Thanks for reporting this error. It looks like this is thrown by the performance analyzer plugin during startup as the security permissions are not initialized when the plugin starts. We will continue to investigate if this can be avoided but subsequent plugin operations should not be throwing this error, and should work as expected. Please let us know if you see any impact on functionality with this error.

**Comment by shivdoshi** [comment]
Resolving. Feel free to re-open if you have any more question.
