### ISSUE TITLE
Exception for audit log index when "action.auto_create_index" is disabled

### ISSUE THREAD

**Issue by tocw** [opendistro-for-elasticsearch/security#141]
Hi, 
I get the following exception after disabling the index auto creation in Elastic:

```
[2019-09-18T15:00:58,082][ERROR][c.a.o.s.a.s.InternalESSink] [***********] Unable to index audit log {"audit_cluster_name":"opendistro","audit_node_name":"********","audit_category":"FAILED_LOGIN","audit_request_origin":"REST","audit_node_id":"********","audit_request_layer":"REST","audit_rest_request_path":"/_opendistro/_security/authinfo","@timestamp":"2019-09-18T15:00:58.081+00:00","audit_request_effective_user_is_admin":false,"audit_format_version":4,"audit_request_remote_address":"172.21.31.102","audit_node_host_address":"172.21.31.105","audit_rest_request_headers":{"Connection":["keep-alive"],"Host":["172.21.31.105:9200"],"Content-Length":["0"]},"audit_request_effective_user":"<NONE>","audit_node_host_name":"172.21.31.105"} due to [security-auditlog-2019.09.18] IndexNotFoundException[no such index [security-auditlog-2019.09.18] and [action.auto_create_index] ([0]) doesn't match]
org.elasticsearch.index.IndexNotFoundException: no such index [security-auditlog-2019.09.18] and [action.auto_create_index] ([0]) doesn't match
        at org.elasticsearch.action.support.AutoCreateIndex.shouldAutoCreate(AutoCreateIndex.java:97) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.bulk.TransportBulkAction.shouldAutoCreate(TransportBulkAction.java:296) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:242) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:93) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:145) ~[elasticsearch-7.1.1.jar:7.1.1]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply0(OpenDistroSecurityFilter.java:189) ~[?:?]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply(OpenDistroSecurityFilter.java:119) ~[?:?]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:143) ~[elasticsearch-7.1.1.jar:7.1.1]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:49) ~[?:?]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:143) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:121) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.bulk.TransportSingleItemBulkWriteAction.doExecute(TransportSingleItemBulkWriteAction.java:69) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.bulk.TransportSingleItemBulkWriteAction.doExecute(TransportSingleItemBulkWriteAction.java:44) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:145) ~[elasticsearch-7.1.1.jar:7.1.1]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply0(OpenDistroSecurityFilter.java:189) ~[?:?]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply(OpenDistroSecurityFilter.java:119) ~[?:?]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:143) ~[elasticsearch-7.1.1.jar:7.1.1]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:65) ~[?:?]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:143) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:121) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:382) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:45) ~[elasticsearch-7.1.1.jar:7.1.1]
        at com.amazon.opendistroforelasticsearch.security.auditlog.sink.InternalESSink.doStore(InternalESSink.java:78) [opendistro_security_advanced_modules-1.1.0.0.jar:1.1.0.0]
        at com.amazon.opendistroforelasticsearch.security.auditlog.sink.AuditLogSink.doStoreWithRetry(AuditLogSink.java:75) [opendistro_security_advanced_modules-1.1.0.0.jar:1.1.0.0]
        at com.amazon.opendistroforelasticsearch.security.auditlog.sink.AuditLogSink.store(AuditLogSink.java:66) [opendistro_security_advanced_modules-1.1.0.0.jar:1.1.0.0]
        at com.amazon.opendistroforelasticsearch.security.auditlog.routing.AsyncStoragePool.lambda$submit$0(AsyncStoragePool.java:62) [opendistro_security_advanced_modules-1.1.0.0.jar:1.1.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
AUDIT_LOG: {
  "audit_cluster_name" : "opendistro",
  "audit_node_name" : "********",
  "audit_category" : "FAILED_LOGIN",
  "audit_request_origin" : "REST",
  "audit_node_id" : "********",
  "audit_request_layer" : "REST",
  "audit_rest_request_path" : "/_opendistro/_security/authinfo",
  "@timestamp" : "2019-09-18T15:00:58.081+00:00",
  "audit_request_effective_user_is_admin" : false,
  "audit_format_version" : 4,
  "audit_request_remote_address" : "172.21.31.102",
  "audit_node_host_address" : "172.21.31.105",
  "audit_rest_request_headers" : {
    "Connection" : [
      "keep-alive"
    ],
    "Host" : [
      "172.21.31.105:9200"
    ],
    "Content-Length" : [
      "0"
    ]
  },
  "audit_request_effective_user" : "<NONE>",
  "audit_node_host_name" : "172.21.31.105"
}
```
It looks like security plugin is not able to create the audit log index.
OpenDistro release: **1.1.0**

**Comment by sujithvm** [comment]
Looks like auto index creation is disabled but writing audit logs to internal_elasticsearch (index) on the same cluster. Please do one of the following
- create the index security-auditlog-*
- change audit log destination to another destination
- disable audit log
