### ISSUE TITLE
Unknown kid when kid contains / 

### ISSUE THREAD

**Issue by yurippe** [opendistro-for-elasticsearch/security#27]
When using OpenID Connect I get this error if the kid contains a `/`
```
com.amazon.dlic.auth.http.jwt.keybyoidc.BadCredentialsException: Unknown kid J4j+I06r0I0vpYnBNucugV8xAPV5\/Xv4uYrrpwwSNK0=
	at com.amazon.dlic.auth.http.jwt.keybyoidc.SelfRefreshingKeySet.getKeyWithKeyId(SelfRefreshingKeySet.java:118) ~[opendistro_security_advanced_modules-0.7.0.0.jar:0.7.0.0]
	at com.amazon.dlic.auth.http.jwt.keybyoidc.SelfRefreshingKeySet.getKey(SelfRefreshingKeySet.java:58) ~[opendistro_security_advanced_modules-0.7.0.0.jar:0.7.0.0]
	at com.amazon.dlic.auth.http.jwt.keybyoidc.JwtVerifier.getVerifiedJwtToken(JwtVerifier.java:41) ~[opendistro_security_advanced_modules-0.7.0.0.jar:0.7.0.0]
	at com.amazon.dlic.auth.http.jwt.AbstractHTTPJwtAuthenticator.extractCredentials0(AbstractHTTPJwtAuthenticator.java:103) 
```
It seems that the forward-slash in the kid is escaped wrong. The real kid should not have `\/` but rather just the `/`

**Comment by shivdoshi** [comment]
@yurippe Can you share more information when you are seeing this issue and any steps to reproduce this?

**Comment by yurippe** [comment]
The only steps I know to reproduce this is to randomly get a kid that contains a `/`character - this happened consistently when trying to integrate with AWS Cognito. I could also confirm that the issue did not occur when the key id did not contain the forward slash.

**Comment by MichelZ** [comment]
@yurippe Can you share the OpenID discovery document URL, or the Document itself?

**Comment by yurippe** [comment]
This is the discovery url: [https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_iee3pUveg/.well-known/openid-configuration](https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_iee3pUveg/.well-known/openid-configuration)

**Comment by MichelZ** [comment]
I can't find the KID you mention in your initial post there:
https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_iee3pUveg/.well-known/jwks.json

That's probably why it fails? <Might> have nothing to do with backslash?

**Comment by yurippe** [comment]
Yes it is not there, but that is because I did some testing to verify that it is in fact the `/` that is the issue. When using this [https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_yWo60V4XY/.well-known/jwks.json](https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_yWo60V4XY/.well-known/jwks.json) it works as expected. (The first kid)

**Comment by dubmusic** [comment]
Hello all, 

I also get a similar error:
[2019-05-07T09:44:05,116][INFO ][c.a.d.a.h.j.AbstractHTTPJwtAuthenticator] [i9oRwfv] Extracting JWT token from eyJraWQiOiJRN3VNNDBUcUxkXC9MVEtSSU5oQlJNejNFXC9JdmpicFA0S25hOStuenN4MTg9IiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoiRjFFazhDb0d6bVRqdl9IbHE4YkJpUSIsInN1YiI6ImRlMTc5NmQ3LTg0ZTMtNDk0Ny1iYTFkLWYyNWVhYzI4OTcwOSIsImNvZ25pdG86Z3JvdXBzIjpbImtpYmFuYV9ncm91cCJdLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiY29nbml0bzpwcmVmZXJyZWRfcm9sZSI6ImFybjphd3M6aWFtOjozMzA4ODEzMDAxNTQ6cm9sZVwvbXN0ZWluLWtpYmFuYS13aXRoLWF1dGhfb3Blbl9yb2xlIiwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tXC9ldS1jZW50cmFsLTFfRU1RR05ONVh5IiwicGhvbmVfbnVtYmVyX3ZlcmlmaWVkIjp0cnVlLCJjb2duaXRvOnVzZXJuYW1lIjoibXN0ZWluIiwiY29nbml0bzpyb2xlcyI6WyJhcm46YXdzOmlhbTo6MzMwODgxMzAwMTU0OnJvbGVcL21zdGVpbi1raWJhbmEtd2l0aC1hdXRoX29wZW5fcm9sZSJdLCJhdWQiOiI2aGJsM3AyYWQ0cGJkNDBxMmVnOGwzZmtzMCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTU3MjIyMjQ0LCJwaG9uZV9udW1iZXIiOiIrNDkxNzQ5MDk4MDcwIiwiZXhwIjoxNTU3MjI1ODQ0LCJpYXQiOjE1NTcyMjIyNDQsImVtYWlsIjoic3RlaW1pY0BhbWF6b24uZGUifQ.LZzAkaGfKcOE8VWW7BOheEI9I3VpBeWq3zMotTjXvrIgRIWHGNSlt05iMKvoKxU8HO7QBpbYp84-mHKJg-WO1htMdUcw-RAJIZMhQzq_gjztmyOKwrD5jpG8-Pm_CTp5ro-9h_pzqIbIBxdiA7Ct6qtE_L9_B02IfaGlPD1pU7IuixODuDjHwgHJ3_XDPoJWpwLlewRSlOHwnTdSe2l_h_m0YrdkjE01ICuwkB2Avlo0TGUVLhjKaetjS_mOB4RwxNW_MRBtlxFO56s8QYZMk65PSX4kff4Vxo1KQKkTWMKR38VRuDRYwJ2961L0mEZJk1JeyR6OTNSuK_jPs4RK6A failed
com.amazon.dlic.auth.http.jwt.keybyoidc.BadCredentialsException: Unknown kid Q7uM40TqLd\/LTKRINhBRMz3E\/IvjbpP4Kna9+nzsx18=

When I look at the configuration URL I am presented with:

curl https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_EMQGNN5Xy/.well-known/openid-configuration | jq

  "authorization_endpoint": "https://bmw-es-test.auth.eu-central-1.amazoncognito.com/oauth2/authorize",
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "issuer": "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_EMQGNN5Xy",
  "jwks_uri": "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_EMQGNN5Xy/.well-known/jwks.json",
  "response_types_supported": [
    "code",
    "token",
    "token id_token"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "phone",
    "profile"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint": "https://bmw-es-test.auth.eu-central-1.amazoncognito.com/oauth2/token",
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "userinfo_endpoint": "https://bmw-es-test.auth.eu-central-1.amazoncognito.com/oauth2/userInfo"
}

And the jwks looks like so:

curl https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_EMQGNN5Xy/.well-known/jwks.json | jq

{
  "keys": [
    {
      "alg": "RS256",
      "e": "AQAB",
      "kid": "Q7uM40TqLd/LTKRINhBRMz3E/IvjbpP4Kna9+nzsx18=",
      "kty": "RSA",
      "n": "v4eW-tQpGS71LPCUIEmIZxVbKI37E-GpbBLrkck0z518tCuLoVSI8PZKIywpjhe1NrpmuJezaa63az3icIUYPLs0Dwk3i8GwgtgE1wZLIC4BcJTqWOAkhEEP4yPd7OX3mTMuJ2BvzB05Yjwa3vy1blhhCFbqnll0-Xhs38lMPlbv2M29ATPXAH9EYZ8e12A8XfTFKfG3Gsj0yfuazJ14ozE6hussu0AsRz9NowS_p1jkqs1K9DHjzgfFxLTjH3Qggz1IRdROqaypVpZMB-FBr6svokA1dsnHbOpuaPB6za0XBq-GghpPjT48dBDCnTWPPgSU07I_No906HlBCzA82w",
      "use": "sig"
    },
    {
      "alg": "RS256",
      "e": "AQAB",
      "kid": "8ZnhNbqPIMzFA/NdiqA/9JcmpDiwZ8rAJuGulNPbEQE=",
      "kty": "RSA",
      "n": "haWIUL92CFs6Cr_fkg8mRiObY67UiUFju2VkCUpttxCFC68gFpZRZIpUKR2catN3SxPbhR3XNLPFVEqKfkwAB0neD3OQ-tsVaOPfIYkmvmWpiB0OgRn_fgBoCP0-w-JgdqTFUNovSB-nDvjXyzZyeJYM4LrlCUNxSBKC79vIKhk-KD-MjQ56bwplWfGDEc5hJxXmUr1jtA_Pk_3oo8fwbO28KRkZhwK7QXX-8R_W1NRFqAk2ppymLwPuQPGMvY5HANyjvA1Okjc7D-67dPpFn6m3JhCBBttkhROmM6JAcPv53JwXq1hM8iV4q-e-mPpvDDU0-ZAwzwvjNJiVN7iyBQ",
      "use": "sig"
    }
  ]
}

Comparing the kids:  Opendistro is logging:

Q7uM40TqLd\/LTKRINhBRMz3E\/IvjbpP4Kna9+nzsx18=

while the actual kid is:  Q7uM40TqLd/LTKRINhBRMz3E/IvjbpP4Kna9+nzsx18=

I am also using Cognito.

**Comment by dubmusic** [comment]
Hello all,

I also get a similar error:
[2019-05-07T09:44:05,116][INFO ][c.a.d.a.h.j.AbstractHTTPJwtAuthenticator] [i9oRwfv] Extracting JWT token from eyJraWQiOiJRN3VNNDBUcUxkXC9MVEtSSU5oQlJNejNFXC9JdmpicFA0S25hOStuenN4MTg9IiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoiRjFFazhDb0d6bVRqdl9IbHE4YkJpUSIsInN1YiI6ImRlMTc5NmQ3LTg0ZTMtNDk0Ny1iYTFkLWYyNWVhYzI4OTcwOSIsImNvZ25pdG86Z3JvdXBzIjpbImtpYmFuYV9ncm91cCJdLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiY29nbml0bzpwcmVmZXJyZWRfcm9sZSI6ImFybjphd3M6aWFtOjozMzA4ODEzMDAxNTQ6cm9sZVwvbXN0ZWluLWtpYmFuYS13aXRoLWF1dGhfb3Blbl9yb2xlIiwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tXC9ldS1jZW50cmFsLTFfRU1RR05ONVh5IiwicGhvbmVfbnVtYmVyX3ZlcmlmaWVkIjp0cnVlLCJjb2duaXRvOnVzZXJuYW1lIjoibXN0ZWluIiwiY29nbml0bzpyb2xlcyI6WyJhcm46YXdzOmlhbTo6MzMwODgxMzAwMTU0OnJvbGVcL21zdGVpbi1raWJhbmEtd2l0aC1hdXRoX29wZW5fcm9sZSJdLCJhdWQiOiI2aGJsM3AyYWQ0cGJkNDBxMmVnOGwzZmtzMCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTU3MjIyMjQ0LCJwaG9uZV9udW1iZXIiOiIrNDkxNzQ5MDk4MDcwIiwiZXhwIjoxNTU3MjI1ODQ0LCJpYXQiOjE1NTcyMjIyNDQsImVtYWlsIjoic3RlaW1pY0BhbWF6b24uZGUifQ.LZzAkaGfKcOE8VWW7BOheEI9I3VpBeWq3zMotTjXvrIgRIWHGNSlt05iMKvoKxU8HO7QBpbYp84-mHKJg-WO1htMdUcw-RAJIZMhQzq_gjztmyOKwrD5jpG8-Pm_CTp5ro-9h_pzqIbIBxdiA7Ct6qtE_L9_B02IfaGlPD1pU7IuixODuDjHwgHJ3_XDPoJWpwLlewRSlOHwnTdSe2l_h_m0YrdkjE01ICuwkB2Avlo0TGUVLhjKaetjS_mOB4RwxNW_MRBtlxFO56s8QYZMk65PSX4kff4Vxo1KQKkTWMKR38VRuDRYwJ2961L0mEZJk1JeyR6OTNSuK_jPs4RK6A failed
com.amazon.dlic.auth.http.jwt.keybyoidc.BadCredentialsException: Unknown kid Q7uM40TqLd/LTKRINhBRMz3E\/IvjbpP4Kna9+nzsx18=

When I look at the configuration URL I am presented with:

curl https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_EMQGNN5Xy/.well-known/openid-configuration | jq

"authorization_endpoint": "https://bmw-es-test.auth.eu-central-1.amazoncognito.com/oauth2/authorize",
"id_token_signing_alg_values_supported": [
"RS256"
],
"issuer": "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_EMQGNN5Xy",
"jwks_uri": "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_EMQGNN5Xy/.well-known/jwks.json",
"response_types_supported": [
"code",
"token",
"token id_token"
],
"scopes_supported": [
"openid",
"email",
"phone",
"profile"
],
"subject_types_supported": [
"public"
],
"token_endpoint": "https://bmw-es-test.auth.eu-central-1.amazoncognito.com/oauth2/token",
"token_endpoint_auth_methods_supported": [
"client_secret_basic",
"client_secret_post"
],
"userinfo_endpoint": "https://bmw-es-test.auth.eu-central-1.amazoncognito.com/oauth2/userInfo"
}

And the jwks looks like so:

curl https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_EMQGNN5Xy/.well-known/jwks.json | jq

{
"keys": [
{
"alg": "RS256",
"e": "AQAB",
"kid": "Q7uM40TqLd/LTKRINhBRMz3E/IvjbpP4Kna9+nzsx18=",
"kty": "RSA",
"n": "v4eW-tQpGS71LPCUIEmIZxVbKI37E-GpbBLrkck0z518tCuLoVSI8PZKIywpjhe1NrpmuJezaa63az3icIUYPLs0Dwk3i8GwgtgE1wZLIC4BcJTqWOAkhEEP4yPd7OX3mTMuJ2BvzB05Yjwa3vy1blhhCFbqnll0-Xhs38lMPlbv2M29ATPXAH9EYZ8e12A8XfTFKfG3Gsj0yfuazJ14ozE6hussu0AsRz9NowS_p1jkqs1K9DHjzgfFxLTjH3Qggz1IRdROqaypVpZMB-FBr6svokA1dsnHbOpuaPB6za0XBq-GghpPjT48dBDCnTWPPgSU07I_No906HlBCzA82w",
"use": "sig"
},
{
"alg": "RS256",
"e": "AQAB",
"kid": "8ZnhNbqPIMzFA/NdiqA/9JcmpDiwZ8rAJuGulNPbEQE=",
"kty": "RSA",
"n": "haWIUL92CFs6Cr_fkg8mRiObY67UiUFju2VkCUpttxCFC68gFpZRZIpUKR2catN3SxPbhR3XNLPFVEqKfkwAB0neD3OQ-tsVaOPfIYkmvmWpiB0OgRn_fgBoCP0-w-JgdqTFUNovSB-nDvjXyzZyeJYM4LrlCUNxSBKC79vIKhk-KD-MjQ56bwplWfGDEc5hJxXmUr1jtA_Pk_3oo8fwbO28KRkZhwK7QXX-8R_W1NRFqAk2ppymLwPuQPGMvY5HANyjvA1Okjc7D-67dPpFn6m3JhCBBttkhROmM6JAcPv53JwXq1hM8iV4q-e-mPpvDDU0-ZAwzwvjNJiVN7iyBQ",
"use": "sig"
}
]
}

Comparing the kids: Opendistro is logging:

Q7uM40TqLd/LTKRINhBRMz3E\/IvjbpP4Kna9+nzsx18=

while the actual kid is: Q7uM40TqLd/LTKRINhBRMz3E/IvjbpP4Kna9+nzsx18=

I am also using Cognito.

**Comment by dubmusic** [comment]
> Unknown kid Q7uM40TqLd\/LTKRINhBRMz3E\/IvjbpP4Kna9+nzsx18=

**Comment by dubmusic** [comment]
I am also seeing this error:

```
failed
com.amazon.dlic.auth.http.jwt.keybyoidc.BadCredentialsException: Unknown kid Q7uM40TqLd\/LTKRINhBRMz3E\/IvjbpP4Kna9+nzsx18=
```

**Comment by hardik-k-shah** [comment]
Thanks for reporting this. 
This seems like a bug to me (security plugin is not escaping forward-slash properly). We will debug this further and propose a fix soon.

**Comment by dubmusic** [comment]
Let me know if there is any further information that you need regarding this issue.

**Comment by cliu123** [comment]
@dubmusic [This PR](https://github.com/opensearch-project/security-dashboards-plugin/pull/749/files) has been merged. Would you please see if you still see this issue in OpenSearch Security 1.0.0.0?
