### ISSUE TITLE
Zipfiles are missing from repos

### ISSUE THREAD

**Issue by VariableDeclared** [opendistro-for-elasticsearch/security#283]
Hi,

With regards to this error message:
```
root@ip-172-31-16-84:/usr/share/elasticsearch# ./bin/elasticsearch-plugin install -b com.amazon.opendistroforelasticsearch:opendistro_security:1.2.1.0
-> Downloading com.amazon.opendistroforelasticsearch:opendistro_security:1.2.1.0 from maven central
Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/amazon/opendistroforelasticsearch/opendistro_security/1.2.1.0/opendistro_security-1.2.1.0.zip
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:379)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:454)
        at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:264)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:229)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

It would seem that the packages are not available for download when using plugin installer. I have noticed this for versions above 1.1.0.0.

Any help would be appreciated,

Cheers

**Comment by sujithvm** [comment]
@VariableDeclared Please install the plugin zip via https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#security 

``` 
bin/elasticsearch-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-security/opendistro_security-1.2.1.0.zip
```
