### ISSUE TITLE
Cannot use X-Opaque-Id together with security plugin

### ISSUE THREAD

**Issue by kaituo** [opendistro-for-elasticsearch/security#342]
The X-Opaque-Id header, when provided on the HTTP request header, would cause security plugin throws exception.

```
[2020-03-31 18:18:07 PDT] [2020-04-01 01:18:07 UTC]
kaituo@ip-10-212-62-48.ec2.internal: /apollo/env/kaituo-swift-dev-ES_7_4AMI-ES2-p001/var/output/logs
% curl -i -H "X-Opaque-Id: 123456" -X GET "localhost:9200/test-index/_search?pretty" -H 'Content-Type: application/json' -d'
quote> {
quote>     "query": {
quote>       "match_all": {}
quote>     }
quote> }
quote> '
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Access-Control-Allow-Origin: *
Content-Length: 893
Server: Jetty(8.1.12.v20130726)

{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "value for key [X-Opaque-Id] already present"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "test-index",
        "node" : "Gp1PnBu-SUCABfaOr1iGaw",
        "reason" : {
          "type" : "illegal_argument_exception",
          "reason" : "value for key [X-Opaque-Id] already present"
        }
      }
    ],
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "value for key [X-Opaque-Id] already present",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "value for key [X-Opaque-Id] already present"
      }
    }
  },
  "status" : 400
}
```

This is the stack trace:

```
[2020-03-31T18:19:12,783][DEBUG][o.e.a.s.TransportSearchAction] [d8d1f09a62577acc2d82bbe3fbe8d49b] #[java.lang.IllegalArgumentException]#[test-index][2], node[Gp1PnBu-SUCABfaOr1iGaw], [P], s[STARTED], a[id=C_baTZC4QK253FZ79dGDew]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[test-index], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={"query":{"match_all":{"boost":1.0}}}}]
java.lang.IllegalArgumentException: value for key [X-Opaque-Id] already present
        at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.putSingleHeader(ThreadContext.java:523) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.putHeaders(ThreadContext.java:533) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.access$300(ThreadContext.java:468) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext.putHeader(ThreadContext.java:343) ~[elasticsearch-7.4.2.jar:7.4.2]
        at com.amazon.opendistroforelasticsearch.security.transport.OpenDistroSecurityInterceptor.sendRequestDecorate(OpenDistroSecurityInterceptor.java:197) ~[?:?]
        at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin$7$2.sendRequest(OpenDistroSecurityPlugin.java:649) ~[?:?]
        at com.amazonaws.elasticsearch.iam.IamTransportRequestSender.sendRequest(IamTransportRequestSender.java:73) ~[?:?]
        at com.amazonaws.elasticsearch.ccs.CrossClusterRequestInterceptor$AddHeaderSender.sendRequest(CrossClusterRequestInterceptor.java:101) ~[?:?]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:602) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:646) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:637) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.search.SearchTransportService.sendExecuteQuery(SearchTransportService.java:137) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.executePhaseOnShard(SearchQueryThenFetchAsyncAction.java:54) ~[elasticsearch-7.4.2.jar:7.4.2]
```

**Comment by kaituo** [comment]
Root cause:

In security plugin, we stashed the context, start with a brand new, empty one, and reinsert headers in a whitelist (mostly security plugin headers).  X-Opaque-Id is whitelisted too and reinserted to the header.

https://github.com/opendistro-for-elasticsearch/security/blob/703253ed58e4471d5573e9bf950637797c534b55/src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java#L125-L178

However, when we stash context, ES actually leaves out everything except X-Opaque-id:

https://github.com/elastic/elasticsearch/blob/42150d3674089f415e0b8c54993aef2a03d016b5/server/src/main/java/org/elasticsearch/common/util/concurrent/ThreadContext.java#L115-L134

Thus, when we re-insert X-Opaque-id, we get exception:

https://github.com/elastic/elasticsearch/blob/42150d3674089f415e0b8c54993aef2a03d016b5/server/src/main/java/org/elasticsearch/common/util/concurrent/ThreadContext.java#L492-L496

**Comment by kaituo** [comment]
Output of src/test/java/com/amazon/opendistroforelasticsearch/security/TaskTests.java 

Test output before the fix:

```
{
  "node_failures" : [
    {
      "type" : "failed_node_exception",
      "reason" : "Failed node [9s58xepNR2Kzk8Ivw11z7A]",
      "node_id" : "9s58xepNR2Kzk8Ivw11z7A",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "value for key [X-Opaque-Id] already present"
      }
    },
    {
      "type" : "failed_node_exception",
      "reason" : "Failed node [5pvpVceLRzWTGfUfbQQmNQ]",
      "node_id" : "5pvpVceLRzWTGfUfbQQmNQ",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "value for key [X-Opaque-Id] already present"
      }
    },
    {
      "type" : "failed_node_exception",
      "reason" : "Failed node [WvIn7DaCT_ytvlBcoeIH8w]",
      "node_id" : "WvIn7DaCT_ytvlBcoeIH8w",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "value for key [X-Opaque-Id] already present"
      }
    }
  ],
  "tasks" : { }
}
```

Test output after the fix:

```
[2020-04-03T13:11:42,169][WARN ][com.amazon.opendistroforelasticsearch.security.ssl.util.SSLCertificateHelper] Certificate chain for alias kirk contains a root certificate
{
  "tasks" : {
    "6s7jrb2ER-WLrbwS7ZBWmg:164" : {
      "node" : "6s7jrb2ER-WLrbwS7ZBWmg",
      "id" : 164,
      "type" : "transport",
      "action" : "cluster:monitor/tasks/lists",
      "start_time_in_millis" : 1585944724440,
      "running_time_in_nanos" : 58306938,
      "cancellable" : false,
      "headers" : {
        "X-Opaque-Id" : "myOpaqueId12"
      },
      "children" : [
        {
          "node" : "6s7jrb2ER-WLrbwS7ZBWmg",
          "id" : 165,
          "type" : "direct",
          "action" : "cluster:monitor/tasks/lists[n]",
          "start_time_in_millis" : 1585944724471,
          "running_time_in_nanos" : 27817593,
          "cancellable" : false,
          "parent_task_id" : "6s7jrb2ER-WLrbwS7ZBWmg:164",
          "headers" : {
            "X-Opaque-Id" : "myOpaqueId12"
          }
        },
        {
          "node" : "drJPUXuoRxSgo2kdbJ2Qfg",
          "id" : 157,
          "type" : "transport",
          "action" : "cluster:monitor/tasks/lists[n]",
          "start_time_in_millis" : 1585944724496,
          "running_time_in_nanos" : 2366253,
          "cancellable" : false,
          "parent_task_id" : "6s7jrb2ER-WLrbwS7ZBWmg:164",
          "headers" : {
            "X-Opaque-Id" : "myOpaqueId12"
          }
        },
        {
          "node" : "SBIBCQaZSjeI7Q9wh4iJOQ",
          "id" : 203,
          "type" : "transport",
          "action" : "cluster:monitor/tasks/lists[n]",
          "start_time_in_millis" : 1585944724490,
          "running_time_in_nanos" : 7518251,
         "cancellable" : false,
          "parent_task_id" : "6s7jrb2ER-WLrbwS7ZBWmg:164",
          "headers" : {
            "X-Opaque-Id" : "myOpaqueId12"
          }
        }
      ]
    }
  }
}
```

The test passes as long as there are more than 2 substrings in the output split by "X-Opaque-Id”.  As you can see above, both outputs before and after the fix satisfy the condition.   

https://github.com/opendistro-for-elasticsearch/security/blob/703253ed58e4471d5573e9bf950637797c534b55/src/test/java/com/amazon/opendistroforelasticsearch/security/TaskTests.java#L44
