### ISSUE TITLE
ES fails to start with AccessControlException

### ISSUE THREAD

**Issue by vrozov** [opendistro-for-elasticsearch/security#369]
After ef6399974b0ffd367f252ad62215eb6cdd618512, ES fails to start with AccessControlException:
```
[2020-04-09T21:44:25,001][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [Vlads-MacBook-Pro.local] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: com.google.common.util.concurrent.UncheckedExecutionException: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.6.1.jar:7.6.1]
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050) ~[?:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[?:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973) ~[?:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957) ~[?:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963) ~[?:?]
	at com.google.common.eventbus.SubscriberRegistry.getAnnotatedMethods(SubscriberRegistry.java:173) ~[?:?]
	at com.google.common.eventbus.SubscriberRegistry.findAllSubscribers(SubscriberRegistry.java:164) ~[?:?]
	at com.google.common.eventbus.SubscriberRegistry.register(SubscriberRegistry.java:74) ~[?:?]
	at com.google.common.eventbus.EventBus.register(EventBus.java:186) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigFactory.registerDCFListener(DynamicConfigFactory.java:227) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigFactory.<init>(DynamicConfigFactory.java:119) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin.createComponents(OpenDistroSecurityPlugin.java:790) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$9(Node.java:456) ~[elasticsearch-7.6.1.jar:7.6.1]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
	at org.elasticsearch.node.Node.<init>(Node.java:459) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.node.Node.<init>(Node.java:257) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.1.jar:7.6.1]
	... 6 more
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_241]
	at java.security.AccessController.checkPermission(AccessController.java:886) ~[?:1.8.0_241]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_241]
	at java.lang.Class.checkMemberAccess(Class.java:2348) ~[?:1.8.0_241]
	at java.lang.Class.getDeclaredMethods(Class.java:1974) ~[?:1.8.0_241]
	at com.google.common.eventbus.SubscriberRegistry.getAnnotatedMethodsNotCached(SubscriberRegistry.java:180) ~[?:?]
	at com.google.common.eventbus.SubscriberRegistry.access$000(SubscriberRegistry.java:54) ~[?:?]
	at com.google.common.eventbus.SubscriberRegistry$1.load(SubscriberRegistry.java:154) ~[?:?]
	at com.google.common.eventbus.SubscriberRegistry$1.load(SubscriberRegistry.java:151) ~[?:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044) ~[?:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[?:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973) ~[?:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957) ~[?:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963) ~[?:?]
	at com.google.common.eventbus.SubscriberRegistry.getAnnotatedMethods(SubscriberRegistry.java:173) ~[?:?]
	at com.google.common.eventbus.SubscriberRegistry.findAllSubscribers(SubscriberRegistry.java:164) ~[?:?]
	at com.google.common.eventbus.SubscriberRegistry.register(SubscriberRegistry.java:74) ~[?:?]
	at com.google.common.eventbus.EventBus.register(EventBus.java:186) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigFactory.registerDCFListener(DynamicConfigFactory.java:227) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigFactory.<init>(DynamicConfigFactory.java:119) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin.createComponents(OpenDistroSecurityPlugin.java:790) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$9(Node.java:456) ~[elasticsearch-7.6.1.jar:7.6.1]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
	at org.elasticsearch.node.Node.<init>(Node.java:459) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.node.Node.<init>(Node.java:257) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.1.jar:7.6.1]
	... 6 more
```

**Comment by vrozov** [comment]
Fixed by #370
