### ISSUE TITLE
problem with self signed cert with oidc

### ISSUE THREAD

**Issue by hermanhmlee** [opendistro-for-elasticsearch/security#442]
i haven't figured out whether this is the right module that handles the OpenID Connect code - it doesn't seem like so please let me know if I should go to another module instead. Since I can't get SAML to work, I am trying OIDC and I get a self-signed cert error when I use OIDC. I already put the CA cert in 

config:
  pemtrustedcas_filepath: /path/to/trusted_cas.pem

as well.

Error from the log:

,"tags":["error","openid"],"pid":XXXXX,"level":"error","error":{"message":"Client request error: self signed certificate","name":"Error","stack":"Error: self signed certificate\n    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket._finishInit (_tls_wrap.js:643:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)","code":"DEPTH_ZERO_SELF_SIGNED_CERT"},"message":"Client request error: self signed certificate"

**Comment by vrozov** [comment]
Looks like kibana is not properly configured.
