### ISSUE TITLE
PKIX path building failed

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [opendistro-for-elasticsearch/security#490]
I'm trying to install the security plugin for ElasticSearch 7.6.1 (running in docker). I have followed the instructions for generating certificates here: https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/generate-certificates/

Then, I try to run initialize the plugin, as per the instructions:
```
./securityadmin.sh -h esserver -p 9300 -cd ../securityconfig/ -icl -nhnv -cacert ../../../config/root-ca.pem -cert ../../../config/admin.pem -key ../../../config/admin-key.pem
```

I get this output, with a "PKIX path building failed" error:
```
Open Distro Security Admin v7
Will connect to esserver:9300 ... done
19:31:43.329 [elasticsearch[_client_][transport_worker][T#1]] ERROR com.amazon.opendistroforelasticsearch.security.ssl.transport.OpenDistroSecuritySSLNettyTransport - Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[?:?]
...
ERR: Cannot connect to Elasticsearch. Please refer to elasticsearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{pRecHMf0T0iHTkxzmCAH1A}{esserver}{172.18.0.2:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:352)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:248)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:394)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:396)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:385)
	at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin.execute(OpenDistroSecurityAdmin.java:520)
	at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin.main(OpenDistroSecurityAdmin.java:153)

```

At the same time, ElasticSearch prints out this message:
```
esserver_1         | {"type": "server", "timestamp": "2020-06-03T19:53:47,289Z", "level": "ERROR", "component": "c.a.o.s.s.t.OpenDistroSecuritySSLNettyTransport", "cluster.name": "reactome-elk", "node.name": "reactome-node-1", "message": "Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown", "cluster.uuid": "zLKklAAmRWmOrRi_8bXYFg", "node.id": "iAwVj8wtTSCKxuUu6RatLw" , 
esserver_1         | "stacktrace": ["javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown",
esserver_1         | "at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]",
esserver_1         | "at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]",
e
...
```

I'm not sure what to do next, as I believe I've followed all of the steps correctly, and I didn't see anything in the trouble-shooting guide about this.

**Comment by vrozov** [comment]
It is necessary to start ES with the configured certificates. If you run it in the docker, please see https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker-security/

**Comment by SolomonShorser-OICR** [comment]
I mounted all of the certificates as that document suggests. One difference is that I did not generate node keys/certificates as it seems to be optional, according to this: https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/generate-certificates/#optional-generate-node-and-client-certificates
I thought the node certificates were optional for me as I'm trying to run a single-node cluster. Should I generate them anyway?

**Comment by vrozov** [comment]
It is better to generate them.

**Comment by SolomonShorser-OICR** [comment]
Ah, never mind. There was an error in the docker-compose file and the config wasn't getting mounted into the container correctly. :facepalm: 

Now, I've got other issues with the kibanaserver user, but I will just post a question in another repo if I can't resolve it soon...
