### ISSUE TITLE
Errors trying to enable saml auth

### ISSUE THREAD

**Issue by ghost** [opendistro-for-elasticsearch/security#496]
I have been trying to enable saml auth in kibana off and on for a few weeks and I keep just getting general redirects to /customerror?type=samlConfigError#/ below is the relevant blocks in my config.yaml in /usr/share/elasticsearch/plugins/opendistro_security/securityconfig:

```
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_file: metadata.xml
              entity_id: http://www.okta.com/exkedev024VvshgHf4x6
            sp:
              entity_id: http://10.16.72.60
            kibana_url: http://10.16.72.60:5601/
            exchange_key: "peuvgOLrjzuhXfjdfhggkewjrkwdnzcydfasdkasdl123123ndwdshdsdsdsfydfskdfsmdfs"
        authentication_backend:
          type: noop
```

/etc/kibana/kibana.yml:

```
server.host: 0.0.0.0
server.xsrf.whitelist: ["/_opendistro/_security/saml/acs"]
logging.verbose: true
opendistro_security.auth.type: "saml"
```

Finally, here's what appears to be a relevant error in /var/log/elasticsearch/elasticsearch.log:
```
[2020-06-08T21:16:57,461][ERROR][c.a.d.a.h.s.HTTPSamlAuthenticator] [ip-10-16-72-60.ec2.internal] Error in reRequestAuthentication()
java.lang.NullPointerException: Cannot invoke "com.amazon.dlic.auth.http.saml.Saml2SettingsProvider.getCached()" because "this.saml2SettingsProvider" is null
	at com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticator.reRequestAuthentication(HTTPSamlAuthenticator.java:164) [opendistro_security-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry.authenticate(BackendRegistry.java:520) [opendistro_security-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityRestFilter.checkAndAuthenticateRequest(OpenDistroSecurityRestFilter.java:146) [opendistro_security-1.8.0.0.jar:1.8.0.0]
...
[2020-06-08T21:16:57,463][WARN ][c.a.o.s.a.BackendRegistry] [ip-10-16-72-60.ec2.internal] Authentication finally failed for null from 127.0.0.1:52074
```

This is on a ec2 instance in my VPC behind an ALB, although I'm testing by using openVPN to go to the instance directly.

Any help would be greatly appreciated. I'm pulling my hair out. I see others having had similar issues but no one has posted what their solution was.

**Comment by vrozov** [comment]
@rcurtis-swanleap Please check logs for another error message: "Error creating HTTPSamlAuthenticator:"

**Comment by vrozov** [comment]
Closing due to inactivity. Please feel free to re-open and provide requested info.
