### ISSUE TITLE
Can't use Let’s Encrypt certificate

### ISSUE THREAD

**Issue by issinsky** [opendistro-for-elasticsearch/security#52]
I run Open Distro for Elasticsearch in Docker container with Docker compose.
When I mount self-signed certificates and CA, Elasticsearch works as expected.
When I mount Let’s Encrypt certificates, I get errors:
```
[2019-05-22T15:33:17,757][ERROR][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [es01] Your keystore or PEM does not contain a key. If you specified a key password, try removing it. If you did not specify a key password, perhaps you need to if the key is in fact password-protected. Maybe you just confused keys and certificates.
...
Caused by: org.elasticsearch.ElasticsearchSecurityException: Error while initializing transport SSL layer from PEM: java.lang.IllegalArgumentException: File does not contain valid private key: /usr/share/elasticsearch/config/node-key.pem
...
Caused by: java.lang.IllegalArgumentException: File does not contain valid private key: /usr/share/elasticsearch/config/node-key.pem
```

Kibana as well as test Nginx and Apache containers work fine with the same pem files.

Here are some validations to show that certificates are fine.

Openssl verify returns OK:
```
openssl verify -verbose -CAfile lets_root_chain.pem fullchain.pem
fullchain.pem: OK
```

lets_root_chain.pem is a concatenation of isrgrootx1.pem.txt (ISRG Root X1 (self-signed)) and letsencryptauthorityx3.pem.txt (Let’s Encrypt Authority X3 (Signed by ISRG Root X1)).

fullchain.pem and privkey.pem are the pair:
```
openssl x509 -noout -modulus -in fullchain.pem | openssl md5
openssl rsa -noout -modulus -in privkey.pem | openssl md5
(stdin)= 8e3628a899bce3a92471e5c99dcbc62c
(stdin)= 8e3628a899bce3a92471e5c99dcbc62c
```

I've tried both wildcard and single host certificates. And of course the key has no password.

elasticsearch.yml
```
...
# Transport layer TLS
opendistro_security.ssl.transport.pemcert_filepath: node-cert.pem
opendistro_security.ssl.transport.pemkey_filepath: node-key.pem
opendistro_security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
opendistro_security.ssl.transport.enforce_hostname_verification: false

# REST layer TLS
opendistro_security.ssl.http.enabled: true
opendistro_security.ssl.http.pemcert_filepath: node-cert.pem
opendistro_security.ssl.http.pemkey_filepath: node-key.pem
opendistro_security.ssl.http.pemtrustedcas_filepath: root-ca.pem
...
```

docker-compose.yml
```
...
    volumes:
      - es-data01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ${SSL_CERT}:/usr/share/elasticsearch/config/node-cert.pem
      - ${SSL_KEY}:/usr/share/elasticsearch/config/node-key.pem
      - ${SSL_CA}:/usr/share/elasticsearch/config/root-ca.pem
...
```
.env:
```
SSL_CA=./lets_root_chain.pem
SSL_CERT=./fullchain.pem
SSL_KEY=./privkey.pem
```

**Comment by coolgooze** [comment]
reporting same issue.

**Comment by jeff-cook** [comment]
Something I ran into with TLS is that ODFE doesn't support some format of certificates. I'm not sure if Lets's Encrypt will support this format for the server key. 

IMPORTANT: Convert these to PKCS#5 v1.5 to work correctly with the JDK. Output from
this command will be used in all the config files.

https://aws.amazon.com/blogs/opensource/add-ssl-certificates-open-distro-for-elasticsearch/

**Comment by sfvolf** [comment]
reporting same issue.

**Comment by mhf-ir** [comment]
Same problem for cfssl on EC PRIVATE KEY

**Comment by lakhansamani** [comment]
Facing the same issue

**Comment by WiXZlo** [comment]
same problem with ssl cert (rsa-4096) generated with cfssl

**Comment by xial-thu** [comment]
installed standalone security plugin to ECK image, met the same problem with ECK generated self-signed certs

**Comment by govindcnd** [comment]
Facing the same issue, with letsencrypt as well comodo certificates. Verified the cert manually on SSL verify which shows success. mean while container failed to pass healthcheck 

Caused by: org.elasticsearch.ElasticsearchSecurityException: Error while initializing transport SSL layer from PEM: java.lang.IllegalArgumentException: File does not contain valid certificates: /usr/share/elasticsearch/config/elk-crt.pem
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.initSSLConfig(DefaultOpenDistroSecurityKeyStore.java:364) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.<init>(DefaultOpenDistroSecurityKeyStore.java:164) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.OpenDistroSecuritySSLPlugin.<init>(OpenDistroSecuritySSLPlugin.java:207) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin.<init>(OpenDistroSecurityPlugin.java:223) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:605) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:556) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:471) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.node.Node.<init>(Node.java:339) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.7.1.jar:6.7.1]
	... 6 more
Caused by: java.lang.IllegalArgumentException: File does not contain valid certificates: /usr/share/elasticsearch/config/elk-crt.pem
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265) ~[?:?]
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:90) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.buildSSLServerContext(DefaultOpenDistroSecurityKeyStore.java:747) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.initSSLConfig(DefaultOpenDistroSecurityKeyStore.java:351) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.<init>(DefaultOpenDistroSecurityKeyStore.java:164) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.OpenDistroSecuritySSLPlugin.<init>(OpenDistroSecuritySSLPlugin.java:207) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin.<init>(OpenDistroSecurityPlugin.java:223) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:605) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:556) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:471) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.node.Node.<init>(Node.java:339) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.7.1.jar:6.7.1]
	... 6 more
Caused by: java.security.cert.CertificateException: found no certificates in input stream
	at io.netty.handler.ssl.PemReader.readCertificates(PemReader.java:98) ~[?:?]
	at io.netty.handler.ssl.PemReader.readCertificates(PemReader.java:64) ~[?:?]
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1071) ~[?:?]
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:263) ~[?:?]
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:90) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.buildSSLServerContext(DefaultOpenDistroSecurityKeyStore.java:747) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.initSSLConfig(DefaultOpenDistroSecurityKeyStore.java:351) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.<init>(DefaultOpenDistroSecurityKeyStore.java:164) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.OpenDistroSecuritySSLPlugin.<init>(OpenDistroSecuritySSLPlugin.java:207) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin.<init>(OpenDistroSecurityPlugin.java:223) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:605) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:556) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:471) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.node.Node.<init>(Node.java:339) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.1.jar:6.7.1]

**Comment by Tarasovych** [comment]
Same issue here. I was following [this guide](https://aws.amazon.com/blogs/opensource/add-ssl-certificates-open-distro-for-elasticsearch/), end up with

> io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by vrozov** [comment]
> Same issue here. I was following [this guide](https://aws.amazon.com/blogs/opensource/add-ssl-certificates-open-distro-for-elasticsearch/), end up with
> 
> > io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Please provide full stack trace here.

**Comment by Tarasovych** [comment]
> 
> Please provide full stack trace here.

Sorry, full stack trace is gone. I changed certificate file permissions and the error was gone. I'm not 100% sure that the problem was with permissions.

I use Docker, certificates folder is binded from host machine. I end up with `a+rx` permissions for the certificates folder, not sure if they are too open. I also tried `o+rx`, but I got

> Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/my-certificates-folder
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/my-certificates-folder
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1840)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2837)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:220)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:129)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:354)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)

After that I went `a+rx`, and there were warnings like

> [WARN ][c.a.o.s.OpenDistroSecurityPlugin] [node1] Directory /usr/share/elasticsearch/config/my-certificates-folder has insecure file permissions (should be 0700)
[WARN ][c.a.o.s.OpenDistroSecurityPlugin] [node1] Directory /usr/share/elasticsearch/config/my-certificates-folder/another-folder has insecure file permissions (should be 0700)
[WARN ][c.a.o.s.OpenDistroSecurityPlugin] [node1] Directory /usr/share/elasticsearch/config/my-certificates-folder/another-folder/domain.com has insecure file permissions (should be 0700)
[WARN ][c.a.o.s.OpenDistroSecurityPlugin] [node1] File /usr/share/elasticsearch/config/my-certificates-folder/another-folder/domain.com/fullchain1.pem has insecure file permissions (should be 0600)

**Comment by QuingKhaos** [comment]
Same issue here when using [step-ca](https://github.com/smallstep/certificates) which [defaults to using ECDSA keys](https://smallstep.com/docs/step-ca/certificate-authority-server-production#sane-cryptographic-defaults).

/cc @mikemaxey @maraino @dopey

**Comment by maraino** [comment]
> /cc @mikemaxey @maraino @dopey for an option on step ca certificate to choose the private key format?

@QuingKhaos I've added an issue for this some time ago https://github.com/smallstep/cli/issues/387, and now I think we should be providing PKCS#8 keys by default.

**Comment by jamestutton** [comment]
Just encase anyone else experiencing this basically 2 issues with LE certs and opendistro-es

First is private key type: Fix is:
```
  privateKey:
    encoding: PKCS8
```

Second is the lack of ca.crt in cert-manager LE secrets.  This can be worked around by setting the ...CASubPath: tls.crt technically at this point to my understand your validating the cert is the cert vs it signed by the ISRG Root X1 but it does allow es to start with LE certs and then those certs be externally valid in the browser.


Full Example


elastic-example-com.yaml
```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-example-com
  namespace: elastic
spec:
  commonName: elastic.example.com
  dnsNames:
  - 'elastic.example.com'
  privateKey:
    encoding: PKCS8
  secretName: elastic-example-com-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

```
values.yml

```
---
elasticsearch:
  ssl:
    transport:
      enabled: true
      existingCertSecret: elastic-example-com-tls
      existingCertSecretCertSubPath: tls.crt
      existingCertSecretKeySubPath: tls.key
      existingCertSecretRootCASubPath: tls.crt
...
...
    opendistro_security.nodes_dn:
      - 'CN=elastic.example.com'
...
```

**Comment by danpawlik** [comment]
Maybe it will help someone to setup Let's Encrypt on Opensearch host:

1. Convert privkey to pkcs8 format:
```
openssl pkcs8 -topk8 -nocrypt -in privkey.pem -out privkey-pkcs8.pem
```

2. Check what identrust signed it:
```
openssl x509 -noout -subject   -in chain.pem
```
In my case result was:
```
subject=C = US, O = Let's Encrypt, CN = R3
```

3. Download CA pem key (it is available here: https://letsencrypt.org/certificates/ ) - my was R3: 
```
curl -SL https://letsencrypt.org/certs/isrgrootx1.pem > isrgrootx1.pem
```

3. Set proper configuration in opensearch.yml
```
plugins.security.ssl.transport.pemcert_filepath: /usr/share/opensearch/config/certs/fullchain.pem
plugins.security.ssl.transport.pemkey_filepath: /usr/share/opensearch/config/certs/privkey-pkcs8.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/opensearch/config/certs/isrgrootx1.pem
plugins.security.ssl.http.pemcert_filepath: /usr/share/opensearch/config/certs/fullchain.pem
plugins.security.ssl.http.pemkey_filepath: /usr/share/opensearch/config/certs/privkey-pkcs8.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/opensearch/config/certs/isrgrootx1.pem
```

4. Do not forget to change/replace admin_dn param. You can check the value by typing:
```
openssl x509 -subject -nameopt RFC2253 -noout -in fullchain.pem | sed 's/subject= //g' | sed 's/subject=//g'
```

then add/replace it to the opensearch.yml file:
```
plugins.security.authcz.admin_dn:
  - CN=mydomain.com
```

**Comment by z3phyrgtr** [comment]
@danpawlik 

I am trying to do the same but it is not working, even with your description.
I got my Let's Encrypt cert files via the cert-manager in a kubernetes cluster.
Since it is not working there, I tried to get it running in a docker-compose where I copied the certificate files (tls.crt and tls.key) to.
But even locally I have a mistake in my config.

Can you explain what is part of the _fullchain.pem_ and _chain.pem_ ?

**Comment by danpawlik** [comment]
> @danpawlik
> 
> I am trying to do the same but it is not working, even with your description. I got my Let's Encrypt cert files via the cert-manager in a kubernetes cluster. Since it is not working there, I tried to get it running in a docker-compose where I copied the certificate files (tls.crt and tls.key) to. But even locally I have a mistake in my config.
> 
> Can you explain what is part of the _fullchain.pem_ and _chain.pem_ ?

`fullchain.pem is a concatenation of cert.pem and chain.pem in one file.` and `chain.pem contains the intermediate certificate`.
Maybe it is worth to try if its working with container deploy and then try on k8s.
You can use 'ansible-role-elastic-recheck' role available on softwarefactory-project.io.

**Comment by z3phyrgtr** [comment]
Thank you, then my two files are correct.

Is it important that only the root-ca is in the file set to: *pemtrustedcas_filepath*?

I'm currently trying to set it up with the certs from k8s in a docker-compose.
Tried different settings, but I will try yours next.
Here is the link to the Post:
https://discuss.opendistrocommunity.dev/t/k8s-define-ssl-certificates-via-secrets/7523/17?u=skunz
