### ISSUE TITLE
Repeatedly  dls_query  does not match (SG 900D) Happened.

### ISSUE THREAD

**Issue by timothynode** [opendistro-for-elasticsearch/security#545]
Frequency: Everyday at UTC 00:00

Behavior: 
`
[2020-07-02T08:00:23,793][ERROR][c.a.o.s.f.OpenDistroSecurityFilter] [hz-es-ssd-254-46-1] Unexpected exception ElasticsearchSecurityException[_opendistro_security_dls_query does not match (SG 900D)]
org.elasticsearch.ElasticsearchSecurityException: _opendistro_security_dls_query does not match (SG 900D)
        at com.amazon.opendistroforelasticsearch.security.privileges.DlsFlsEvaluator.evaluate(DlsFlsEvaluator.java:132) ~[opendistro_security-1.6.0.0.jar:1.6.0.0]
        at com.amazon.opendistroforelasticsearch.security.privileges.PrivilegesEvaluator.evaluate(PrivilegesEvaluator.java:196) ~[opendistro_security-1.6.0.0.jar:1.6.0.0]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply0(OpenDistroSecurityFilter.java:252) [opendistro_security-1.6.0.0.jar:1.6.0.0]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply(OpenDistroSecurityFilter.java:119) [opendistro_security-1.6.0.0.jar:1.6.0.0]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:151) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:129) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation.doRun(TransportBulkAction.java:497) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.bulk.TransportBulkAction.executeBulk(TransportBulkAction.java:610) [elasticsearch-7.6.1.jar:7.6.1]
`

Impact: will cause node failure and index creation failure.

Any info about SG 900D? what does it mean?

Here is something i found when i look deeper.

All logstash or kibana connect to ES via nginx. But nginx does not report any 500 error. 
Looks strange cause ElasticsearchSecurityException says it's internal server error.

**Comment by Anthony7774** [comment]
@timothynode Did you get this resolved? Do you have any dls set up in roles? Also which version of edfe/os are you running?

**Comment by swapnilsvaidya** [comment]
I am also hitting this issue.
I am having dls setup in my role
