### ISSUE TITLE
SAML auth not working in 1.9.0.1

### ISSUE THREAD

**Issue by shawnz** [opendistro-for-elasticsearch/security#617]
Hi there, after upgrading to 1.9.0.1, SAML auth stopped working for me. Downgrading to 1.9.0.0 fixed the issue. Here is the message I got:

```
[2020-08-03T14:29:10,029][INFO ][o.o.s.m.r.i.AbstractReloadingMetadataResolver] [node-1] Metadata Resolver SamlHTTPMetadataResolver com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticator_1: New metadata successfully loaded for 'https://...'
[2020-08-03T14:29:10,053][INFO ][o.o.s.m.r.i.AbstractReloadingMetadataResolver] [node-1] Metadata Resolver SamlHTTPMetadataResolver com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticator_1: Next refresh cycle for metadata provider 'https://...' will occur on '2020-08-03T21:29:09.760Z' ('2020-08-03T17:29:09.760-04:00' local time)
[2020-08-03T14:29:10,139][WARN ][c.a.o.s.s.ReflectionHelper] [node-1] Unable to enable 'com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticator' due to java.lang.reflect.InvocationTargetException
[2020-08-03T14:29:10,140][ERROR][c.a.o.s.s.DynamicConfigModelV7] [node-1] Unable to initialize auth domain saml_auth_domain=AuthcDomain [http_enabled=true, transport_enabled=false, order=1, http_authenticator=HttpAuthenticator [challenge=true, type=saml, config={idp={metadata_url=https://..., entity_id=https://...}, sp={entity_id=https://...}, kibana_url=https://..., roles_key=..., exchange_key=...}], authentication_backend=AuthcBackend [type=noop, config={}], description=Authenticate via SAML] due to ElasticsearchException[java.lang.reflect.InvocationTargetException]; nested: InvocationTargetException; nested: ExceptionInInitializerError; nested: AccessControlException[access denied ("java.util.PropertyPermission" "org.apache.xml.security.ignoreLineBreaks" "write")];
org.elasticsearch.ElasticsearchException: java.lang.reflect.InvocationTargetException
        at com.amazon.opendistroforelasticsearch.security.support.ReflectionHelper.instantiateAAA(ReflectionHelper.java:244) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigModelV7.newInstance(DynamicConfigModelV7.java:338) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigModelV7.buildAAA(DynamicConfigModelV7.java:255) [opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigModelV7.<init>(DynamicConfigModelV7.java:60) [opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigFactory.onChange(DynamicConfigFactory.java:207) [opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.opendistroforelasticsearch.security.configuration.ConfigurationRepository.notifyAboutChanges(ConfigurationRepository.java:334) [opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.opendistroforelasticsearch.security.configuration.ConfigurationRepository.reloadConfiguration0(ConfigurationRepository.java:323) [opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.opendistroforelasticsearch.security.configuration.ConfigurationRepository.reloadConfiguration(ConfigurationRepository.java:306) [opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.opendistroforelasticsearch.security.configuration.ConfigurationRepository$1.run(ConfigurationRepository.java:193) [opendistro_security-1.9.0.1.jar:1.9.0.1]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at com.amazon.opendistroforelasticsearch.security.support.ReflectionHelper.instantiateAAA(ReflectionHelper.java:233) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        ... 9 more
Caused by: java.lang.ExceptionInInitializerError
        at com.onelogin.saml2.settings.SettingsBuilder.loadCertificateFromProp(SettingsBuilder.java:534) ~[java-saml-core-2.5.0.jar:?]
        at com.onelogin.saml2.settings.SettingsBuilder.loadCertificateListFromProp(SettingsBuilder.java:578) ~[java-saml-core-2.5.0.jar:?]
        at com.onelogin.saml2.settings.SettingsBuilder.loadIdpSetting(SettingsBuilder.java:243) ~[java-saml-core-2.5.0.jar:?]
        at com.onelogin.saml2.settings.SettingsBuilder.build(SettingsBuilder.java:202) ~[java-saml-core-2.5.0.jar:?]
        at com.onelogin.saml2.settings.SettingsBuilder.build(SettingsBuilder.java:177) ~[java-saml-core-2.5.0.jar:?]
        at com.amazon.dlic.auth.http.saml.Saml2SettingsProvider.get(Saml2SettingsProvider.java:99) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.dlic.auth.http.saml.Saml2SettingsProvider.getCached(Saml2SettingsProvider.java:114) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticator.<init>(HTTPSamlAuthenticator.java:128) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at com.amazon.opendistroforelasticsearch.security.support.ReflectionHelper.instantiateAAA(ReflectionHelper.java:233) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        ... 9 more
Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "org.apache.xml.security.ignoreLineBreaks" "write")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:897) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:322) ~[?:?]
        at java.lang.System.setProperty(System.java:894) ~[?:?]
        at com.onelogin.saml2.util.Util.<clinit>(Util.java:116) ~[java-saml-core-2.5.0.jar:?]
        at com.onelogin.saml2.settings.SettingsBuilder.loadCertificateFromProp(SettingsBuilder.java:534) ~[java-saml-core-2.5.0.jar:?]
        at com.onelogin.saml2.settings.SettingsBuilder.loadCertificateListFromProp(SettingsBuilder.java:578) ~[java-saml-core-2.5.0.jar:?]
        at com.onelogin.saml2.settings.SettingsBuilder.loadIdpSetting(SettingsBuilder.java:243) ~[java-saml-core-2.5.0.jar:?]
        at com.onelogin.saml2.settings.SettingsBuilder.build(SettingsBuilder.java:202) ~[java-saml-core-2.5.0.jar:?]
        at com.onelogin.saml2.settings.SettingsBuilder.build(SettingsBuilder.java:177) ~[java-saml-core-2.5.0.jar:?]
        at com.amazon.dlic.auth.http.saml.Saml2SettingsProvider.get(Saml2SettingsProvider.java:99) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.dlic.auth.http.saml.Saml2SettingsProvider.getCached(Saml2SettingsProvider.java:114) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        at com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticator.<init>(HTTPSamlAuthenticator.java:128) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at com.amazon.opendistroforelasticsearch.security.support.ReflectionHelper.instantiateAAA(ReflectionHelper.java:233) ~[opendistro_security-1.9.0.1.jar:1.9.0.1]
        ... 9 more
```

Perhaps it has something to do with #603. 

Thanks, Shawn

**Comment by dream11harsimran** [comment]
Hi

The package which is present at Opendistro docs (https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#security) says it 1.9.0.0 (https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-security/opendistro_security-1.9.0.0.zip) but this is different zip archive which we get from the release page (https://github.com/opendistro-for-elasticsearch/security/releases/download/v1.9.0.0/artifacts.zip).

The one at docs also breaks for the SAML.

Thanks
Rubal

**Comment by vrozov** [comment]
Please try https://github.com/opendistro-for-elasticsearch/security/releases/tag/v1.9.0.2
