### ISSUE TITLE
"failed to turn off translog retention" after upgrade

### ISSUE THREAD

**Issue by gferrette** [opendistro-for-elasticsearch/security#651]
Hello,

After upgrade Opendistro from version 1.0.2 to version 1.7.0, on nodes startup, its appearing on the logs the message below:

[2020-08-14T10:54:21,893][WARN ][o.e.i.s.IndexShard       ] [machine] [.tasks][0] failed to turn off translog retention
org.apache.lucene.store.AlreadyClosedException: engine is closed
        at org.elasticsearch.index.shard.IndexShard.getEngine(IndexShard.java:2528) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard.trimTranslog(IndexShard.java:1106) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard$3.doRun(IndexShard.java:1944) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.1.jar:7.6.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]

This message is appearing for several indices, but the indices/shards are not corrupted and they are on green state, but on every startup those messages are appearing on the logs.

Is there any way to solve this issue?

Thanks in advance.

Gabriel.

**Comment by dinusX** [comment]
Hi @gferrette ,
would you be able to change the log level to DEBUG and paste again the stack trace ?

**Comment by gferrette** [comment]
Hello @dinusX !

Follow below the stack trace with DEBUG log level:

[2020-08-18T10:52:54,720][DEBUG][o.e.c.s.MasterService    ] [machine] publishing cluster state version [482]
[2020-08-18T10:52:54,711][DEBUG][o.e.i.t.Translog         ] [machine] [.kibana_1298139586_usuarioteste][0] open uncommitted translog checkpoint Checkpoint{offset=55, numOps=0, generation=4, minSeqNo=-1, maxSeqNo=-1, globalCheckpoint=0, minTranslogGeneration=3, trimmedAboveSeqNo=-2}
[2020-08-18T10:52:54,722][DEBUG][o.e.i.t.Translog         ] [machine] [.kibana_1298139586_usuarioteste][0] recovered local translog from checkpoint Checkpoint{offset=55, numOps=0, generation=4, minSeqNo=-1, maxSeqNo=-1, globalCheckpoint=0, minTranslogGeneration=3, trimmedAboveSeqNo=-2}
[2020-08-18T10:52:54,707][DEBUG][o.e.i.t.Translog         ] [machine] [.kibana_1276559883_testesubidaversao_1][0] recovered local translog from checkpoint Checkpoint{offset=55, numOps=0, generation=7, minSeqNo=-1, maxSeqNo=-1, globalCheckpoint=0, minTranslogGeneration=5, trimmedAboveSeqNo=-2}
[2020-08-18T10:52:54,733][DEBUG][o.e.i.t.Translog         ] [machine] [.kibana_1298139586_usuarioteste][0] recovered local translog from checkpoint Checkpoint{offset=55, numOps=0, generation=4, minSeqNo=-1, maxSeqNo=-1, globalCheckpoint=0, minTranslogGeneration=3, trimmedAboveSeqNo=-2}
[2020-08-18T10:52:54,736][DEBUG][o.e.c.c.PublicationTransportHandler] [machine] received diff cluster state version [482] with uuid [kPQDh3sIRgOcMbRvFdobqQ], diff size [252]
[2020-08-18T10:52:54,744][DEBUG][o.e.i.e.Engine           ] [machine] [security-auditlog-2020.08.17][0] Safe commit [CommitPoint{segment[segments_4], userData[{history_uuid=6F_7duGVQfWQ09WpZ8xQVw, local_checkpoint=0, max_seq_no=0, max_unsafe_auto_id_timestamp=-1, min_retained_seq_no=1, sync_id=KGFfdj5NSmu7Cmu82PshqQ, translog_generation=3, translog_uuid=sE5JbcYESma2dXRitoTphw}]}], last commit [CommitPoint{segment[segments_4], userData[{history_uuid=6F_7duGVQfWQ09WpZ8xQVw, local_checkpoint=0, max_seq_no=0, max_unsafe_auto_id_timestamp=-1, min_retained_seq_no=1, sync_id=KGFfdj5NSmu7Cmu82PshqQ, translog_generation=3, translog_uuid=sE5JbcYESma2dXRitoTphw}]}]
[2020-08-18T10:52:54,760][DEBUG][o.e.g.PersistedClusterStateService] [machine] writing cluster state took [0ms]; wrote global metadata [false] and metadata for [0] indices and skipped [27] unchanged indices
[2020-08-18T10:52:54,762][DEBUG][o.e.i.e.Engine           ] [machine] [.kibana_1276559883_testesubidaversao_1][0] Safe commit [CommitPoint{segment[segments_4], userData[{history_uuid=FAQMiebKTBiYHhXci0HgUA, local_checkpoint=0, max_seq_no=0, max_unsafe_auto_id_timestamp=-1, min_retained_seq_no=1, sync_id=ZBSi3AaQQKScPFa8XIreQw, translog_generation=5, translog_uuid=3Zfcvlm2QjmmJBIeNnzKeQ}]}], last commit [CommitPoint{segment[segments_4], userData[{history_uuid=FAQMiebKTBiYHhXci0HgUA, local_checkpoint=0, max_seq_no=0, max_unsafe_auto_id_timestamp=-1, min_retained_seq_no=1, sync_id=ZBSi3AaQQKScPFa8XIreQw, translog_generation=5, translog_uuid=3Zfcvlm2QjmmJBIeNnzKeQ}]}]
[2020-08-18T10:52:54,763][DEBUG][o.e.c.s.ClusterApplierService] [machine] processing [Publication{term=21, version=482}]: execute
[2020-08-18T10:52:54,764][DEBUG][o.e.c.s.ClusterApplierService] [machine] cluster state updated, version [482], source [Publication{term=21, version=482}]
[2020-08-18T10:52:54,764][DEBUG][o.e.c.NodeConnectionsService] [machine] connected to {machine}{PNjawAAZRj-olrAsLoq8TQ}{0VAaApceT7ylZ8IhxY-Bug}{10.0.2.191}{10.0.2.191:9300}{dim}
[2020-08-18T10:52:54,764][DEBUG][o.e.c.s.ClusterApplierService] [machine] apply cluster state with version 482
[2020-08-18T10:52:54,767][DEBUG][o.e.i.s.IndexShard       ] [machine] [.tasks][0] turn off the translog retention for the replication group [.tasks][0] as it starts using retention leases exclusively in peer recoveries
[2020-08-18T10:52:54,768][DEBUG][o.e.c.s.ClusterApplierService] [machine] set locally applied cluster state to version 482
[2020-08-18T10:52:54,769][DEBUG][o.e.c.s.ClusterApplierService] [machine] processing [Publication{term=21, version=482}]: took [0s] done applying updated cluster state (version: 482, uuid: kPQDh3sIRgOcMbRvFdobqQ)
[2020-08-18T10:52:54,769][DEBUG][o.e.c.c.C.CoordinatorPublication] [machine] publication ended successfully: Publication{term=21, version=482}
[2020-08-18T10:52:54,769][DEBUG][o.e.c.s.MasterService    ] [machine] took [0s] to notify listeners on successful publication of cluster state (version: 482, uuid: kPQDh3sIRgOcMbRvFdobqQ) for [cluster_reroute(async_shard_fetch)]
[2020-08-18T10:52:54,775][DEBUG][o.e.i.e.Engine           ] [machine] [.kibana_1298139586_usuarioteste][0] Safe commit [CommitPoint{segment[segments_4], userData[{history_uuid=YBSLGiwlQeiK3RocGmqtwQ, local_checkpoint=0, max_seq_no=0, max_unsafe_auto_id_timestamp=-1, min_retained_seq_no=1, sync_id=Tmc9nBuJRaOExp3UzLc3Mg, translog_generation=3, translog_uuid=AJle9vsoRZ-HAKiYeCHd8g}]}], last commit [CommitPoint{segment[segments_4], userData[{history_uuid=YBSLGiwlQeiK3RocGmqtwQ, local_checkpoint=0, max_seq_no=0, max_unsafe_auto_id_timestamp=-1, min_retained_seq_no=1, sync_id=Tmc9nBuJRaOExp3UzLc3Mg, translog_generation=3, translog_uuid=AJle9vsoRZ-HAKiYeCHd8g}]}]
[2020-08-18T10:52:54,792][DEBUG][o.e.i.e.Engine           ] [machine] [.tasks][0] Safe commit [CommitPoint{segment[segments_a], userData[{history_uuid=FlCD17y_Qeay5P2wxsfYOA, local_checkpoint=3, max_seq_no=3, max_unsafe_auto_id_timestamp=-1, min_retained_seq_no=4, sync_id=589jUf1WRcuWeIxbW4Ox7Q, translog_generation=23, translog_uuid=65fd-Z8BT0qPvJa45rf7Tw}]}], last commit [CommitPoint{segment[segments_a], userData[{history_uuid=FlCD17y_Qeay5P2wxsfYOA, local_checkpoint=3, max_seq_no=3, max_unsafe_auto_id_timestamp=-1, min_retained_seq_no=4, sync_id=589jUf1WRcuWeIxbW4Ox7Q, translog_generation=23, translog_uuid=65fd-Z8BT0qPvJa45rf7Tw}]}]
[2020-08-18T10:52:54,788][WARN ][o.e.i.s.IndexShard       ] [machine] [.tasks][0] failed to turn off translog retention
org.apache.lucene.store.AlreadyClosedException: engine is closed
        at org.elasticsearch.index.shard.IndexShard.getEngine(IndexShard.java:2528) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard.trimTranslog(IndexShard.java:1106) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard$3.doRun(IndexShard.java:1944) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.1.jar:7.6.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
[2020-08-18T10:52:54,824][DEBUG][o.e.i.s.IndexShard       ] [machine] [security-auditlog-2020.08.17][0] state: [RECOVERING]->[POST_RECOVERY], reason [post recovery from shard_store]
[2020-08-18T10:52:54,824][DEBUG][o.e.i.s.IndexShard       ] [machine] [security-auditlog-2020.08.17][0] recovery completed from [shard_store], took [287ms]
[2020-08-18T10:52:54,825][DEBUG][o.e.c.a.s.ShardStateAction] [machine] sending [internal:cluster/shard/started] to [PNjawAAZRj-olrAsLoq8TQ] for shard entry [StartedShardEntry{shardId [[security-auditlog-2020.08.17][0]], allocationId [W-rGbGb5TMigtXbkl3t60g], primary term [3], message [after existing store recovery; bootstrap_history_uuid=false]}]
[2020-08-18T10:52:54,826][DEBUG][o.e.c.a.s.ShardStateAction] [machine] [security-auditlog-2020.08.17][0] received shard started for [StartedShardEntry{shardId [[security-auditlog-2020.08.17][0]], allocationId [W-rGbGb5TMigtXbkl3t60g], primary term [3], message [after existing store recovery; bootstrap_history_uuid=false]}]
[2020-08-18T10:52:54,827][DEBUG][o.e.c.s.MasterService    ] [machine] executing cluster state update for [shard-started StartedShardEntry{shardId [[security-auditlog-2020.08.17][0]], allocationId [W-rGbGb5TMigtXbkl3t60g], primary term [3], message [after existing store recovery; bootstrap_history_uuid=false]}[StartedShardEntry{shardId [[security-auditlog-2020.08.17][0]], allocationId [W-rGbGb5TMigtXbkl3t60g], primary term [3], message [after existing store recovery; bootstrap_history_uuid=false]}]]


Thanks in advance!

**Comment by dinusX** [comment]
From the above logs it seems that you have an index ".tasks" that is failing during ES process boot-up.
- Is this index healthy "green" ?
- Is this index used by any of your plugins ? Maybe that plugin has some bug.
- Can you try maybe re-indexing the index to see if it helps? You'll have to do it twice in order to keep the same name. https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

**Comment by gferrette** [comment]
Hello @dinusX !

Thanks for replying.

This error is occurring in several indexes, not only in .tasks. The .tasks index is in green state, but i have removed this index .tasks, because it is recreated as ES needs it. The error continues on other indexes as below:

[2020-08-18T17:53:34,022][DEBUG][o.e.c.s.ClusterApplierService] [machine] processing [Publication{term=24, version=635}]: execute
[2020-08-18T17:53:34,022][DEBUG][o.e.c.s.ClusterApplierService] [machine] cluster state updated, version [635], source [Publication{term=24, version=635}]
[2020-08-18T17:53:34,022][DEBUG][o.e.c.NodeConnectionsService] [machine] connected to {machine}{PNjawAAZRj-olrAsLoq8TQ}{jOVOPUGCT0mHN2QRYj4Y1Q}{10.0.2.191}{10.0.2.191:9300}{dim}
[2020-08-18T17:53:34,022][DEBUG][o.e.c.s.ClusterApplierService] [machine] applying settings from cluster state with version 635
[2020-08-18T17:53:34,022][DEBUG][o.e.c.s.ClusterApplierService] [machine] apply cluster state with version 635
[2020-08-18T17:53:34,023][DEBUG][o.e.i.s.IndexShard       ] [machine] [security-auditlog-2020.06.15][0] state: [POST_RECOVERY]->[STARTED], reason [global state is [STARTED]]
[2020-08-18T17:53:34,023][DEBUG][o.e.i.s.IndexShard       ] [machine] [.kibana_-532334581_publicoredmine_2][0] turn off the translog retention for the replication group [.kibana_-532334581_publicoredmine_2][0] as it starts using retention leases exclusively in peer recoveries
[2020-08-18T17:53:34,023][DEBUG][o.e.c.a.s.ShardStateAction] [machine] sending [internal:cluster/shard/started] to [PNjawAAZRj-olrAsLoq8TQ] for shard entry [StartedShardEntry{shardId [[.kibana_-532334581_publicoredmine_2][0]], allocationId [2IgravwzSFCNRA-BY4eJBw], primary term [22], message [master {machine}{PNjawAAZRj-olrAsLoq8TQ}{jOVOPUGCT0mHN2QRYj4Y1Q}{10.0.2.191}{10.0.2.191:9300}{dim} marked shard as initializing, but shard state is [POST_RECOVERY], mark shard as started]}]
[2020-08-18T17:53:34,024][DEBUG][o.e.c.a.s.ShardStateAction] [machine] [.kibana_-532334581_publicoredmine_2][0] received shard started for [StartedShardEntry{shardId [[.kibana_-532334581_publicoredmine_2][0]], allocationId [2IgravwzSFCNRA-BY4eJBw], primary term [22], message [master {machine}{PNjawAAZRj-olrAsLoq8TQ}{jOVOPUGCT0mHN2QRYj4Y1Q}{10.0.2.191}{10.0.2.191:9300}{dim} marked shard as initializing, but shard state is [POST_RECOVERY], mark shard as started]}]
[2020-08-18T17:53:34,024][DEBUG][o.e.i.s.IndexShard       ] [machine] [.kibana_-532334581_publicoredmine_1][0] turn off the translog retention for the replication group [.kibana_-532334581_publicoredmine_1][0] as it starts using retention leases exclusively in peer recoveries
[2020-08-18T17:53:34,024][DEBUG][o.e.c.a.s.ShardStateAction] [machine] sending [internal:cluster/shard/started] to [PNjawAAZRj-olrAsLoq8TQ] for shard entry [StartedShardEntry{shardId [[.kibana_-532334581_publicoredmine_1][0]], allocationId [-EIVcT1GQEy3cnSYVpCiGA], primary term [22], message [master {machine}{PNjawAAZRj-olrAsLoq8TQ}{jOVOPUGCT0mHN2QRYj4Y1Q}{10.0.2.191}{10.0.2.191:9300}{dim} marked shard as initializing, but shard state is [POST_RECOVERY], mark shard as started]}]
[2020-08-18T17:53:34,024][DEBUG][o.e.c.a.s.ShardStateAction] [machine] [.kibana_-532334581_publicoredmine_1][0] received shard started for [StartedShardEntry{shardId [[.kibana_-532334581_publicoredmine_1][0]], allocationId [-EIVcT1GQEy3cnSYVpCiGA], primary term [22], message [master {machine}{PNjawAAZRj-olrAsLoq8TQ}{jOVOPUGCT0mHN2QRYj4Y1Q}{10.0.2.191}{10.0.2.191:9300}{dim} marked shard as initializing, but shard state is [POST_RECOVERY], mark shard as started]}]
[2020-08-18T17:53:34,025][DEBUG][o.e.i.s.IndexShard       ] [machine] [.kibana_92668751_admin_1][0] turn off the translog retention for the replication group [.kibana_92668751_admin_1][0] as it starts using retention leases exclusively in peer recoveries
[2020-08-18T17:53:34,025][DEBUG][o.e.c.s.ClusterApplierService] [machine] set locally applied cluster state to version 635
[2020-08-18T17:53:34,029][WARN ][o.e.i.s.IndexShard       ] [machine] [.kibana_92668751_admin_1][0] failed to turn off translog retention
org.apache.lucene.store.AlreadyClosedException: engine is closed
        at org.elasticsearch.index.shard.IndexShard.getEngine(IndexShard.java:2528) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard.trimTranslog(IndexShard.java:1106) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard$3.doRun(IndexShard.java:1944) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.1.jar:7.6.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
[2020-08-18T17:53:34,033][DEBUG][o.e.i.e.Engine           ] [machine] [.kibana_92668751_admin_1][0] Safe commit [CommitPoint{segment[segments_4], userData[{history_uuid=2dgYcvEuRpSjF2naPHfXyA, local_checkpoint=0, max_seq_no=0, max_unsafe_auto_id_timestamp=-1, min_retained_seq_no=1, sync_id=uSgr5MU4QH6yju-GsoF9zA, translog_generation=3, translog_uuid=kyHNsR0nQIGnBo3_O1fAYA}]}], last commit [CommitPoint{segment[segments_4], userData[{history_uuid=2dgYcvEuRpSjF2naPHfXyA, local_checkpoint=0, max_seq_no=0, max_unsafe_auto_id_timestamp=-1, min_retained_seq_no=1, sync_id=uSgr5MU4QH6yju-GsoF9zA, translog_generation=3, translog_uuid=kyHNsR0nQIGnBo3_O1fAYA}]}]



All the indexes that this error is ocurring are in green state.

**Comment by dinusX** [comment]
If I'm not mistaken , the following commit should fix your warning messages: https://github.com/elastic/elasticsearch/pull/57063

This was fixed in ES 7.7.1+

From the description it doesn't seem to be a bug, but just an unnecessary warning message.

**Comment by gferrette** [comment]
Hello @dinusX !

It seems it's only a warning message according to this thread.

Thanks for your help and for clarifying our questions!
