### ISSUE TITLE
DLS security example in documentation doesn't work

### ISSUE THREAD

**Issue by robmartin-scibite** [opendistro-for-elasticsearch/security#863]
Attempted to implement permission based DLS using docker container `amazon/opendistro-for-elasticsearch:1.10.1` as described in the official [documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/document-level-security/#parameter-substitution). 

```
PUT _opendistro/_security/api/internalusers/user1
{
  "password": "asdf",
  "backend_roles": ["abac"],
  "attributes": {
    "permissions": "\"att1\", \"att2\", \"att3\""
  }
}
```

Added role (and role mapping)
```
PUT _opendistro/_security/api/roles/abac
{
  "index_permissions": [{
    "index_patterns": [
      "*"
    ],
    "dls": "{\"terms_set\": {\"security_attributes\": {\"terms\": [\"${attr.internal.permissions}\"], \"minimum_should_match_script\": {\"source\": \"doc['security_attributes'].values.length\"}}}}",
    "allowed_actions": [
      "read"
    ]
  }]
}
```

Performed query
```
GET /test_index/_search
```

Returns
```{
    "error": {
        "root_cause": [
            {
                "type": "exception",
                "reason": "failed to wrap searcher"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "test_index",
                "node": "RMx_gz1RQDS2vObTJ1q_wQ",
                "reason": {
                    "type": "exception",
                    "reason": "failed to wrap searcher",
                    "caused_by": {
                        "type": "i_o_exception",
                        "reason": "java.util.concurrent.ExecutionException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('a' (code 97)): was expecting comma to separate Array entries\n at [Source: (StringReader); line: 1, column: 53]",
                        "caused_by": {
                            "type": "execution_exception",
                            "reason": "com.fasterxml.jackson.core.JsonParseException: Unexpected character ('a' (code 97)): was expecting comma to separate Array entries\n at [Source: (StringReader); line: 1, column: 53]",
                            "caused_by": {
                                "type": "json_parse_exception",
                                "reason": "Unexpected character ('a' (code 97)): was expecting comma to separate Array entries\n at [Source: (StringReader); line: 1, column: 53]"
                            }
                        }
                    }
                }
            }
        ]
    },
    "status": 500
}
```

And I can see from the logs
```
[2020-12-01T08:05:49,738][TRACE][c.a.o.s.r.IndexResolverReplacer] [b412d89c194e] Finally resolved for SearchRequest: Resolved [aliases=[], allIndices=[test_index], types=[*], originalRequested=[test_index], remoteIndices=[]]
[2020-12-01T08:05:49,738][DEBUG][c.a.o.s.f.OpenDistroSecurityFilter] [b412d89c194e] PrivEvalResponse [allowed=true, missingPrivileges=[], allowedFlsFields=null, maskedFields=null, queries={*=[{"terms_set": {"security_attributes": {"terms": [""att1", "att2", "att3""], "minimum_should_match_script": {"source": "doc['security_attributes'].values.length"}}}}], test_index=[{"terms_set": {"security_attributes": {"terms": [""att1", "att2", "att3""], "minimum_should_match_script": {"source": "doc['security_attributes'].values.length"}}}}]}]
[2020-12-01T08:05:49,739][TRACE][c.a.o.s.a.i.AuditLogImpl ] [b412d89c194e] Check category:GRANTED_PRIVILEGES, action:indices:data/read/search, effectiveUser:user1, request:SearchRequest
[2020-12-01T08:05:49,739][TRACE][c.a.o.s.a.i.AuditLogImpl ] [b412d89c194e] Skipped audit log message because category GRANTED_PRIVILEGES not enabled
[2020-12-01T08:05:49,739][TRACE][c.a.o.s.a.i.AuditLogImpl ] [b412d89c194e] Check category:INDEX_EVENT, action:indices:data/read/search, effectiveUser:user1, request:SearchRequest
[2020-12-01T08:05:49,823][WARN ][r.suppressed             ] [b412d89c194e] path: /test_index/_search, params: {index=test_index}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:551) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:309) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:582) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:393) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:68) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:245) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:403) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:638) [elasticsearch-7.9.1.jar:7.9.1]
	at com.amazon.opendistroforelasticsearch.security.transport.OpenDistroSecurityInterceptor$RestoringTransportResponseHandler.handleException(OpenDistroSecurityInterceptor.java:277) [opendistro_security-1.10.1.0.jar:1.10.1.0]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1172) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1281) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1255) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:61) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:56) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:51) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:414) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:710) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.1.jar:7.9.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.elasticsearch.ElasticsearchException: failed to wrap searcher
	at org.elasticsearch.index.shard.IndexShard.wrapSearcher(IndexShard.java:1274) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:1261) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:1249) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:721) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:713) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:669) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:632) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:429) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.access$200(SearchService.java:136) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:396) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:412) ~[elasticsearch-7.9.1.jar:7.9.1]
	... 6 more
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('a' (code 97)): was expecting comma to separate Array entries
 at [Source: (StringReader); line: 1, column: 53]
	at com.amazon.opendistroforelasticsearch.security.configuration.DlsQueryParser.parse(DlsQueryParser.java:103) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityFlsDlsIndexSearcherWrapper.dlsFlsWrap(OpenDistroSecurityFlsDlsIndexSearcherWrapper.java:108) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityIndexSearcherWrapper.apply(OpenDistroSecurityIndexSearcherWrapper.java:94) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityIndexSearcherWrapper.apply(OpenDistroSecurityIndexSearcherWrapper.java:54) ~[?:?]
	at org.elasticsearch.index.shard.IndexShard.wrapSearcher(IndexShard.java:1291) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.wrapSearcher(IndexShard.java:1269) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:1261) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:1249) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:721) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:713) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:669) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:632) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:429) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.access$200(SearchService.java:136) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:396) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:412) ~[elasticsearch-7.9.1.jar:7.9.1]
	... 6 more
Caused by: java.util.concurrent.ExecutionException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('a' (code 97)): was expecting comma to separate Array entries
 at [Source: (StringReader); line: 1, column: 53]
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:526) ~[?:?]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:487) ~[?:?]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83) ~[?:?]
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:196) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2311) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044) ~[?:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4870) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.DlsQueryParser.parse(DlsQueryParser.java:84) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityFlsDlsIndexSearcherWrapper.dlsFlsWrap(OpenDistroSecurityFlsDlsIndexSearcherWrapper.java:108) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityIndexSearcherWrapper.apply(OpenDistroSecurityIndexSearcherWrapper.java:94) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityIndexSearcherWrapper.apply(OpenDistroSecurityIndexSearcherWrapper.java:54) ~[?:?]
	at org.elasticsearch.index.shard.IndexShard.wrapSearcher(IndexShard.java:1291) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.wrapSearcher(IndexShard.java:1269) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:1261) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:1249) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:721) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:713) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:669) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:632) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:429) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.access$200(SearchService.java:136) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:396) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:412) ~[elasticsearch-7.9.1.jar:7.9.1]
	... 6 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('a' (code 97)): was expecting comma to separate Array entries
 at [Source: (StringReader); line: 1, column: 53]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840) ~[jackson-core-2.10.4.jar:2.10.4]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712) ~[jackson-core-2.10.4.jar:2.10.4]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637) ~[jackson-core-2.10.4.jar:2.10.4]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2293) ~[jackson-core-2.10.4.jar:2.10.4]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689) ~[jackson-core-2.10.4.jar:2.10.4]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:52) ~[elasticsearch-x-content-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.query.TermsQueryBuilder.parseValues(TermsQueryBuilder.java:405) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.query.TermsSetQueryBuilder.fromXContent(TermsSetQueryBuilder.java:178) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchModule.lambda$registerQuery$16(SearchModule.java:942) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:140) ~[elasticsearch-x-content-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:385) ~[elasticsearch-x-content-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.query.AbstractQueryBuilder.parseInnerQueryBuilder(AbstractQueryBuilder.java:320) ~[elasticsearch-7.9.1.jar:7.9.1]
	at com.amazon.opendistroforelasticsearch.security.configuration.DlsQueryParser$1.call(DlsQueryParser.java:89) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.DlsQueryParser$1.call(DlsQueryParser.java:84) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4875) ~[?:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044) ~[?:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4870) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.DlsQueryParser.parse(DlsQueryParser.java:84) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityFlsDlsIndexSearcherWrapper.dlsFlsWrap(OpenDistroSecurityFlsDlsIndexSearcherWrapper.java:108) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityIndexSearcherWrapper.apply(OpenDistroSecurityIndexSearcherWrapper.java:94) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityIndexSearcherWrapper.apply(OpenDistroSecurityIndexSearcherWrapper.java:54) ~[?:?]
	at org.elasticsearch.index.shard.IndexShard.wrapSearcher(IndexShard.java:1291) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.wrapSearcher(IndexShard.java:1269) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:1261) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:1249) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:721) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:713) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:669) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:632) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:429) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.access$200(SearchService.java:136) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:396) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:412) ~[elasticsearch-7.9.1.jar:7.9.1]
	... 6 more

```

Note the DLS query looks very wrong:
```
{
  "terms_set": {
    "security_attributes": {
      "terms": [
        ""att1", 
        "att2", 
        "att3""
      ],
      "minimum_should_match_script": {
        "source": "doc['security_attributes'].values.length"
      }
    }
  }
}
```

Also similar issues when reading an attribute from a JWT claim which is multi valued

**Comment by DanielHabenicht** [comment]
Seems like there are multiple mistakes: 

1. The Attribute array has a pair of double quotes to much, as seen in you example `""att1", "att2", "att3""`.
2. The painless query is wrong `doc['security_attributes'].values.length` must be `doc['security_attributes'].length`

All in all the query should be: 
```http
PUT {{baseUrl}}_opendistro/_security/api/roles/abac HTTP/1.1
content-type: application/json
Authorization: Basic admin:admin

{
  "index_permissions": [{
    "index_patterns": [
      "indicarus*"
    ],
    "dls": "{\"terms_set\": {\"security_attributes\": {\"terms\": [${attr.internal.permissions}], \"minimum_should_match_script\": {\"source\": \"doc['security_attributes'].length\"}}}}",
    "allowed_actions": [
      "read"
    ]
  }]
}

```
