### ISSUE TITLE
Exception when loading Permissions?

### ISSUE THREAD

**Issue by micheljung** [opendistro-for-elasticsearch/security#990]
I'm using `amazon/opendistro-for-elasticsearch:1.10.1` and `amazon/opendistro-for-elasticsearch-kibana:1.10.1`

I successfully configured SAML authentication but now I'm struggling with authorization.

securityconfig/config.yml:
```yml
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      internal_auth:
        order: 0
        description: "HTTP basic authentication using the internal user database"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      saml_auth:
        order: 1
        description: "SAML provider"
        http_enabled: true
        transport_enabled: false
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: https://adfs.example.com/FederationMetadata/2007-06/FederationMetadata.xml
              entity_id: http://adfs.example.com/adfs/services/trust
            sp:
              entity_id: application-kibana
            kibana_url: https://kibana.example.com
            roles_key: http://schemas.microsoft.com/ws/2008/06/identity/claims/role
            exchange_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        authentication_backend:
          type: noop
```

roles.yml:
```yml
_meta:
  type: "roles"
  config_version: 2

application_admin:
  reserved: true
  hidden: false
  cluster_permissions:
    - "unlimited"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "unlimited"
  tenant_permissions:
    - tenant_patterns:
        - "*"
  static: false

application_analyst:
  reserved: true
  hidden: false
  index_permissions:
    - index_patterns:
        - "transaction-*"
  tenant_permissions:
    - tenant_patterns:
        - "analyst_*"
      allowed_actions:
        - "kibana_all_write"
  static: false
```

roles_mapping.yml:
```yml
_meta:
  type: "rolesmapping"
  config_version: 2

platin_analyst:
  reserved: false
  hidden: false
  backend_roles:
    - "APPLICATION-ANALYST"

all_access:
  reserved: true
  hidden: false
  backend_roles:
    - "APPLICATION-ADMIN"

application_admin:
  reserved: true
  hidden: false
  backend_roles:
    - "APPLICATION-ADMIN"

readall:
  reserved: true
  hidden: false
  backend_roles:
    - "APPLICATION-DEV"

kibana_server:
  reserved: true
  hidden: false
  users:
    - "kibanaserver"
```

Login is successful, the user is available and all backend roles are listed. However, things don't really work in Kibana and I get this in the elasticsearch logs:

```
[2021-01-21T07:57:45,583][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:45,607][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:45,614][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:45,633][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:45,652][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:47,075][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:47,080][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:47,080][WARN ][stderr                   ] [odfe.example.com] java.lang.UnsupportedOperationException
[2021-01-21T07:57:47,081][WARN ][stderr                   ] [odfe.example.com]     at java.base/java.util.Collections$UnmodifiableMap.put(Collections.java:1473)
[2021-01-21T07:57:47,081][WARN ][stderr                   ] [odfe.example.com]     at com.amazon.opendistroforelasticsearch.security.dlic.rest.api.PermissionsInfoAction$1.accept(PermissionsInfoAction.java:110)
[2021-01-21T07:57:47,081][WARN ][stderr                   ] [odfe.example.com]     at com.amazon.opendistroforelasticsearch.security.dlic.rest.api.PermissionsInfoAction$1.accept(PermissionsInfoAction.java:95)
[2021-01-21T07:57:47,081][WARN ][stderr                   ] [odfe.example.com]     at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:115)
[2021-01-21T07:57:47,082][WARN ][stderr                   ] [odfe.example.com]     at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityRestFilter$1.handleRequest(OpenDistroSecurityRestFilter.java:116)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:236)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:318)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:176)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at com.amazon.opendistroforelasticsearch.security.ssl.http.netty.ValidatingDispatcher.dispatchRequest(ValidatingDispatcher.java:63)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:318)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:372)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:308)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:42)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:28)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:58)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2021-01-21T07:57:47,083][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2021-01-21T07:57:47,084][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2021-01-21T07:57:47,085][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[2021-01-21T07:57:47,085][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2021-01-21T07:57:47,085][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2021-01-21T07:57:47,085][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[2021-01-21T07:57:47,085][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[2021-01-21T07:57:47,085][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[2021-01-21T07:57:47,085][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
[2021-01-21T07:57:47,085][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
[2021-01-21T07:57:47,090][WARN ][stderr                   ] [odfe.example.com]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[2021-01-21T07:57:47,090][WARN ][stderr                   ] [odfe.example.com]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[2021-01-21T07:57:47,090][WARN ][stderr                   ] [odfe.example.com]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-01-21T07:57:47,091][WARN ][stderr                   ] [odfe.example.com]     at java.base/java.lang.Thread.run(Thread.java:832)
[2021-01-21T07:57:47,108][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:47,113][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:47,506][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:47,510][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:47,561][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:47,565][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:47,566][INFO ][c.a.o.s.p.PrivilegesEvaluator] [odfe.example.com] No index-level perm match for User [name=myuser, backend_roles=[APPLICATION-ADMIN, APPLICATION-DEV, Domain Users], requestedTenant=__user__] Resolved [aliases=[.kibana_68514327_myuser], allIndices=[.kibana_68514327_myuser_773], types=[*], originalRequested=[.kibana_68514327_myuser, .kibana_68514327_myuser_773], remoteIndices=[]] [Action [indices:data/read/mget[shard]]] [RolesChecked [own_index]]
[2021-01-21T07:57:47,566][INFO ][c.a.o.s.p.PrivilegesEvaluator] [odfe.example.com] No permissions for [indices:data/read/mget[shard]]
[2021-01-21T07:57:47,657][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2021-01-21T07:57:47,668][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [odfe.example.com] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
```

Aside from the exception, **No index-level perm match for User** concerns me. Is it a result of the exception?
Why does my user have no permissions?

**Comment by micheljung** [comment]
Posting issues always helps finding the problem. My `roles.yml` and `roles_mapping.yml` were mounted to elasticsearch's config directory instead of the one of the security plugin.
